#!/usr/bin/env tsx
/**
 * Seed 15 modernist/fun appetizer recipes.
 * Safe to re-run — skips existing titles.
 */
import Database from 'better-sqlite3';
import path from 'path';
import { ulid } from 'ulid';

const DB_PATH = path.join(process.cwd(), 'chew.db');
const db = new Database(DB_PATH);
const now = () => Math.floor(Date.now() / 1000);

type Recipe = {
  title: string;
  chef: string;
  description: string;
  cuisine: string;
  difficulty: 'easy' | 'medium' | 'hard';
  prepTimeMin: number;
  cookTimeMin: number;
  servings: number;
  ingredients: string[];
  steps: string[];
  source_url: string | null;
  image_url: string | null;
};

const RECIPES: Recipe[] = [
  {
    title: 'Liquid Olives (Spherical Olives)',
    chef: 'José Andrés / The Bazaar',
    description: "Uncured green olive juice is blended with sodium gluconate and dropped into a sodium alginate bath to form perfect liquid-filled spheres that look exactly like real olives. When placed on the tongue, the thin gel membrane bursts and floods the mouth with intense, concentrated olive flavor. The technique, reverse spherification, was pioneered by Ferran Adrià at elBulli and is José Andrés's most celebrated homage to his mentor. They are served on tasting spoons alongside traditional stuffed olives to heighten the visual deception.",
    cuisine: 'Modernist / Spanish',
    difficulty: 'hard',
    prepTimeMin: 60,
    cookTimeMin: 30,
    servings: 8,
    ingredients: [
      '200g uncured green olive juice (pressed from pitted Verdial or Castelvetrano olives)',
      '2g sodium gluconate',
      '0.5g xanthan gum',
      '1000ml filtered water',
      '5g sodium alginate',
      'Extra virgin olive oil, for coating',
      'Fleur de sel, to finish',
    ],
    steps: [
      'Pit the olives and press or blend them, then strain through a fine sieve to obtain 200g of clear olive juice.',
      'Using an immersion blender, blend the sodium gluconate into the olive juice until fully dissolved. Add xanthan gum and blend again; strain and refrigerate 1 hour to remove air bubbles.',
      'Prepare the alginate bath: blend sodium alginate into 1000ml filtered water, refrigerate uncovered 24 hours to fully hydrate and degas.',
      'Pour the alginate bath into a wide, shallow container. Using a round teaspoon or spherification spoon, scoop the olive mixture and gently lower it into the bath; hold submerged 2 minutes.',
      'Carefully remove each sphere with a slotted spoon and rinse in two successive clean water baths.',
      'Transfer finished spheres to a container of lightly salted olive oil until service.',
      'Serve on ceramic tasting spoons with a drop of olive oil and a few grains of fleur de sel.',
    ],
    source_url: 'https://www.thebazaar.com/news-item/bazaar-classics-liquid-olives/',
    image_url: 'https://images.getbento.com/accounts/81bb1875cf6e20eae65ebdfd8c190b75/media/images/68457SLS_Olives_and_Liquid_Olives_2.jpeg?w=1000&fit=crop&auto=compress,format&cs=origin&h=562',
  },
  {
    title: 'Black Truffle Explosion',
    chef: 'Grant Achatz / Alinea',
    description: "A razor-thin pasta ravioli encases a warm sphere of liquid black truffle juice, butter, and truffle oil set in gelatin; when bitten, the liquid erupts in the mouth like a truffle-scented geyser. The concept was inspired by Chinese soup dumplings and developed while Achatz was at The French Laundry, later becoming the signature dish that launched Alinea. The ravioli is topped with a fresh Périgord truffle slice, wilted romaine, and shaved Parmigiano-Reggiano, all served on a single-bite spoon. Heating causes the gelatin to melt, transforming the sphere into hot, buttery liquid at the exact moment the pasta is broken.",
    cuisine: 'Modernist / New American',
    difficulty: 'hard',
    prepTimeMin: 120,
    cookTimeMin: 30,
    servings: 8,
    ingredients: [
      '4 silver gelatin sheets (160 bloom)',
      '240ml black truffle juice (e.g., Savini Tartufi)',
      '1g kosher salt',
      '28g unsalted butter, cubed',
      '5ml white truffle oil',
      "200g '00' flour",
      '3 egg yolks plus 1 whole egg',
      '30ml whole milk',
      '10ml olive oil',
      'Cornmeal, for dusting',
      '1 fresh Périgord black truffle, thinly sliced on mandoline',
      '50g Parmigiano-Reggiano, shaved',
      '2 heads baby romaine, cut in 1-inch strips',
      '30g unsalted butter (for wilting romaine)',
    ],
    steps: [
      'Soak gelatin sheets in ice water 5 minutes. Bring truffle juice and salt to a boil; remove from heat and whisk in cubed butter until incorporated. Add truffle oil. Dissolve softened gelatin in the warm liquid.',
      'Cool to room temperature, pour into hemispheric silicone molds (3cm diameter), filling each halfway. Refrigerate 2 hours until firmly set.',
      "Make pasta: whisk together eggs, milk, and olive oil; gradually incorporate into flour to form a smooth dough. Knead 15 minutes, rest covered 45 minutes.",
      'Roll pasta through machine to setting 3 (thin but sturdy). Unmold truffle spheres; place on pasta sheet spaced 4cm apart. Brush around each sphere with egg yolk.',
      'Lay a second pasta sheet over the top; press firmly around each sphere to seal. Cut with a 4cm round cutter, crimp edges. Refrigerate on cornmeal-lined tray.',
      'To serve: boil ravioli gently 3–4 minutes until pasta is cooked and interior liquefies. Briefly toss in a pan with butter, water, truffle slices, and romaine.',
      'Place each ravioli flat-side up on a serving spoon. Top with a truffle slice, rolled romaine, and a Parmesan shaving. Serve immediately.',
    ],
    source_url: 'https://alineaphile.com/2009/01/black-truffle-explosion-romaine-parmesan/',
    image_url: null,
  },
  {
    title: 'Hot Potato, Cold Potato',
    chef: 'Grant Achatz / Alinea',
    description: "A paraffin wax bowl holds cold black truffle–scented potato soup, while a steel pin suspends a hot butter-poached potato sphere above the surface along with frozen butter, Parmesan, chive, and a black truffle wafer. The diner pulls the pin free, the hot components tumble into the cold soup, and the entire bowl is consumed in a single slurp — a textural and thermal explosion in one mouthful. The dish plays deliberately on the surprising contrast of temperatures and the transformation that happens the instant the pin is removed. It is one of Alinea's most emblematic amuse-bouches and a masterpiece of theatrical tableside service.",
    cuisine: 'Modernist / New American',
    difficulty: 'hard',
    prepTimeMin: 60,
    cookTimeMin: 30,
    servings: 8,
    ingredients: [
      '400g Yukon Gold potatoes, peeled and diced',
      '240ml black truffle juice',
      '120ml heavy cream',
      '15ml white truffle oil',
      'Kosher salt, to taste',
      '4 medium Yukon Gold potatoes (for potato spheres)',
      '150g clarified butter (for cooking spheres)',
      '80g unsalted butter, cut into 1cm cubes and frozen',
      '80g Parmigiano-Reggiano, cut into 1cm cubes',
      '1 fresh Périgord black truffle, thinly sliced',
      'Fresh chives, cut on the bias into 1cm pieces',
      'Maldon sea salt flakes',
      '8 paraffin wax bowls',
    ],
    steps: [
      'Simmer diced potatoes in truffle juice about 20 minutes until tender. Add cream, return to simmer. Blend until smooth, stream in truffle oil; season. Strain and refrigerate until very cold.',
      'Using a 2cm melon baller, scoop potato spheres from whole potatoes. Gently cook in clarified butter over low heat about 20 minutes, turning occasionally, until tender and golden. Keep warm.',
      'Thread each serving pin in sequence: frozen butter cube, Parmesan cube, chive piece, warm potato sphere, and a truffle slice draped over the top. Season potato with Maldon salt.',
      'Pour 30ml cold soup into each paraffin bowl.',
      'Pierce each pin through the side of the bowl so the potato cluster hangs above the soup.',
      'Present immediately. Instruct the diner to pull the pin free, then consume the entire bowl in one motion.',
    ],
    source_url: 'https://alineaphile.com/2008/12/hot-potato-cold-potato-black-truffle-parmesan/',
    image_url: 'https://www.allenhemberger.com/alinea/wp-content/uploads/2009/08/20090802_alinea_0050.jpg',
  },
  {
    title: 'Bacon and Egg Ice Cream',
    chef: 'Heston Blumenthal / The Fat Duck',
    description: "Milk infused overnight with grilled smoked bacon is transformed into a rich custard base, which is injected into empty eggshells and then scrambled tableside in liquid nitrogen so it sets instantly into ice cream that mimics the texture of scrambled eggs. The dish debuted at The Fat Duck in 2000 and deliberately plays on the familiar comfort of a British fry-up while completely subverting every expectation of texture and temperature. Caramelized brioche soldiers and orange marmalade complete the breakfast tableau, making it one of the most photographed and discussed dishes in modernist cuisine history.",
    cuisine: 'Modernist / British',
    difficulty: 'hard',
    prepTimeMin: 60,
    cookTimeMin: 90,
    servings: 6,
    ingredients: [
      '400g sweet-cured smoked back bacon',
      '1 litre full-cream milk',
      '30g semi-skimmed milk powder',
      '24 large egg yolks',
      '120g unrefined caster sugar',
      '6 medium eggs (shells sterilized and emptied)',
      '400g dry ice, crushed',
      'Orange marmalade, to serve',
      '1 loaf brioche, crusts removed, cut into soldiers',
      'Clarified butter, for frying',
      'Golden caster sugar, for caramelizing',
    ],
    steps: [
      "Preheat grill; grill bacon 5–7 minutes until crisp. Drain, cut into strips, place in a bowl, pour milk over, refrigerate overnight.",
      'Next day, add milk powder to bacon-infused milk, simmer gently. Blend egg yolks and sugar; combine with warm milk. Heat to 85°C. Pass through fine sieve into a clean container set over iced water. Cool completely.',
      'Punch small holes top and bottom of each emptied eggshell; sterilize in boiling water 45 minutes. Fill shells with custard base using a syringe; plug holes with pastry dough.',
      'Fry brioche soldiers in clarified butter until golden; drain. Melt sugar in a pan until caramelized; toss soldiers to coat. Cool on a silicone mat.',
      'To serve: crack a filled egg into a cold saucepan. Add crushed dry ice gradually while stirring continuously for about 1 minute until the mixture scrambles into ice cream.',
      'Plate ice cream topped with marmalade and crispy bacon bits. Serve alongside caramelized brioche soldiers.',
    ],
    source_url: 'https://www.sbs.com.au/food/recipe/heston-blumenthals-bacon-and-egg-ice-cream/whz97nklu',
    image_url: null,
  },
  {
    title: 'Snail Porridge',
    chef: 'Heston Blumenthal / The Fat Duck',
    description: "Vibrant green parsley-infused snail butter stirred through creamy oat porridge, topped with braised snails, thin-cut Parma ham, and a fennel salad dressed in walnut oil and sherry vinegar. The dish confronts diners with two ingredients — snails and porridge — that carry associations of blandness or squeamishness, then delivers a dish of extraordinary savory depth and verdant freshness. Blumenthal treated the oats as he would risotto rice, using the snail-enriched chicken stock as the cooking liquid, and the snail butter as a finishing enrichment. The result is simultaneously elegant and mischievous, one of The Fat Duck's most celebrated starters.",
    cuisine: 'Modernist / British',
    difficulty: 'hard',
    prepTimeMin: 30,
    cookTimeMin: 780,
    servings: 1,
    ingredients: [
      '150g chicken wings',
      '12 cooked snails (plus 6 for serving)',
      '1/2 onion, peeled and thinly sliced',
      '1/2 fennel bulb, finely sliced',
      '1 celery stick, finely sliced',
      '50g button mushrooms, finely sliced',
      '2 garlic cloves',
      '1 bouquet garni (bay, thyme, rosemary)',
      '100g unsalted butter, room temperature',
      '10g Dijon mustard',
      '2g salt',
      '50g flat-leaf parsley, chopped and frozen',
      '20g Parma ham (plus 1 slice for serving)',
      '10g porridge oats',
      'Sherry vinegar and walnut oil, for dressing',
    ],
    steps: [
      'Make stock: blanch chicken wings in cold water, drain, return to pot with snails, vegetables, and bouquet garni. Simmer gently 1 hour. Strain and reserve.',
      'Make snail butter: finely chop mushrooms, onion, and garlic. Sweat in half the butter until soft. Blend with remaining butter, Dijon mustard, frozen parsley, Parma ham, snails, and salt until smooth. Roll in cling film and refrigerate.',
      'To serve: heat 200ml stock; add oats, stir constantly 2 minutes until absorbed and creamy. Beat in 40g snail butter and the reserved snails; season.',
      'Shred Parma ham thinly; slice fennel paper thin. Dress fennel with sherry vinegar and walnut oil.',
      'Spoon porridge into a warm bowl; arrange snails on top. Crown with shredded ham and fennel salad. Serve immediately.',
    ],
    source_url: 'https://bigspud.co.uk/heston-blumenthals-snail-porridge/',
    image_url: 'https://i0.wp.com/bigspud.co.uk/wp-content/uploads/2023/11/snail-porridge-thumbnail-860-x-290-px.png?fit=860%2C290&ssl=1',
  },
  {
    title: 'Meat Fruit (Mandarin Chicken Liver Parfait)',
    chef: 'Heston Blumenthal / Dinner by Heston',
    description: "A silky chicken liver parfait enriched with Madeira, Ruby Port, and brandy is molded into perfect spheres, then triple-dipped in a translucent mandarin gelée tinted with paprika extract to create an object indistinguishable from a ripe mandarin — complete with a real leaf and stalk. The dish is inspired by a medieval British recipe for 'Pome Dorres' (apples of gold) circa 1500, bridging six centuries of culinary history with cutting-edge modernist technique. Dinner guests reach for what they think is a citrus fruit and instead cut into one of the most refined and unctuous parfaits imaginable. It became the most photographed dish of 2011 and a permanent fixture at Dinner by Heston.",
    cuisine: 'Modernist / British',
    difficulty: 'hard',
    prepTimeMin: 1440,
    cookTimeMin: 120,
    servings: 6,
    ingredients: [
      '100g finely sliced shallots',
      '3g minced garlic',
      '15g thyme sprigs',
      '150g dry Madeira',
      '150g Ruby Port',
      '75g White Port',
      '50g brandy',
      '18g salt',
      '400g chicken livers, cleaned',
      '240g eggs',
      '300g unsalted butter, melted',
      '500g mandarin purée',
      '80g glucose syrup',
      '45g gelatin leaves, bloomed',
      '0.4g mandarin essential oil',
      '1.5g paprika extract (for color)',
      'Real mandarin stalks and leaves, for garnish',
    ],
    steps: [
      'Combine shallots, garlic, thyme, and all alcohols; marinate 24 hours. Reduce liquid in a pan until nearly evaporated; cool.',
      'Blend eggs, reduction, and salted livers until smooth; pass through fine sieve. Gradually incorporate melted butter while blending. Vacuum-seal in sous vide bags.',
      'Cook in a bain-marie at 100°C until the center reaches 64°C. Cool completely; refrigerate 24 hours.',
      'Mold parfait into 6cm hemispheres; freeze solid. Unmold, torch flat sides briefly, and press pairs together around a popsicle stick to form spheres. Refreeze.',
      'Make mandarin jelly: warm purée and glucose to 60°C; dissolve bloomed gelatin. Add mandarin oil and paprika extract; strain through fine sieve. Cool to 27°C.',
      'Dip each frozen parfait sphere into the jelly three times (returning to freezer between dips) to build a 2–3mm mandarin-like skin.',
      'Defrost in refrigerator minimum 6 hours. Insert stalk and leaf garnish; serve on a wooden board.',
    ],
    source_url: 'https://www.signaturedishes.net/recipes/meat-fruit.html',
    image_url: null,
  },
  {
    title: 'Salmon Poached in a Liquorice Gel',
    chef: 'Heston Blumenthal / The Fat Duck',
    description: "Fresh salmon is coated in a translucent liquorice gellan gel and then gently vacuum-cooked at 42°C for 45 minutes — an application of sous vide so precise that every molecule of moisture is preserved. The liquorice and salmon pairing is rooted in Blumenthal's research into flavor compounds; both share the same anisic aldehyde, making them naturally complementary. The dish is finished with hand-extracted grapefruit cells, vanilla mayonnaise, white asparagus, aged balsamic, and Manni olive oil — each element chosen to create a layered interplay of anise, citrus, and umami. It is one of the most technically demanding starters in The Fat Duck's long repertoire.",
    cuisine: 'Modernist / British',
    difficulty: 'hard',
    prepTimeMin: 30,
    cookTimeMin: 45,
    servings: 4,
    ingredients: [
      '4 salmon fillets (120g each), skinless',
      '1.6 liters low-calcium mineral water',
      '4 pure liquorice sticks (concentrated extract)',
      '4g Gellan F',
      '2g Gellan LT100',
      '4 egg yolks',
      '15ml Chardonnay vinegar reduction',
      'Seeds of 1 vanilla pod',
      '10g Dijon mustard',
      '200ml grapeseed oil',
      '8 white asparagus spears, peeled, cut to 8cm',
      '2 pink grapefruits, cells extracted by hand',
      '20ml aged balsamic vinegar (12–15 year)',
      '20ml Manni extra virgin olive oil',
      'Toasted coriander seeds',
    ],
    steps: [
      'Boil mineral water with liquorice sticks 10 minutes; blend and sieve to obtain a clear, intensely flavored liquorice stock.',
      'Keep stock hot (above 70°C); blend in Gellan F and Gellan LT100.',
      'Dip each salmon fillet 2–4 times in the hot liquorice gel, allowing a thin translucent layer to form between each dip.',
      'Vacuum-seal each coated fillet and cook in a water bath at 42°C for 45 minutes.',
      'Make vanilla mayonnaise: blend egg yolks, vinegar reduction, vanilla seeds, and mustard; stream in oil until emulsified. Season.',
      'Cook asparagus in olive oil over gentle heat until tender. Extract grapefruit cells by hand.',
      'Plate salmon with a quenelle of vanilla mayonnaise, asparagus spears, grapefruit cells, drops of aged balsamic, olive oil, and toasted coriander.',
    ],
    source_url: 'https://thebigfatundertaking.wordpress.com/2010/01/03/12-salmon-poached-in-liqourice-gel/',
    image_url: null,
  },
  {
    title: 'Scrambled Egg Ravioli',
    chef: 'Wylie Dufresne / wd~50',
    description: "Scrambled eggs blended with cream cheese and gelatin are piped into square silicone molds and frozen solid, then thawed to order to produce a ravioli 'filling' that heats from frozen to the perfect creamy-soft scrambled egg texture mid-service. A separately prepared egg yolk, set sous vide at 70°C inside a plastic casing to form a long golden cylinder, is sliced into inch-long pieces that serve as the pasta-free 'wrapper.' The plate is completed with pickled kanpachi, torched avocado cream, and crispy potato brunoise — a dish that deconstructs the form of pasta entirely while remaining unmistakably breakfast. Dufresne considered it one of the purest expressions of his philosophy: find the essential character of a dish and rebuild it from first principles.",
    cuisine: 'Modernist / New American',
    difficulty: 'hard',
    prepTimeMin: 120,
    cookTimeMin: 30,
    servings: 6,
    ingredients: [
      '8 large eggs (for scrambled filling)',
      '60g cream cheese',
      '2g kosher salt',
      'Pinch of cayenne pepper',
      '4g gelatin sheets, bloomed',
      '6 additional egg yolks (for yolk pasta)',
      'Salt and cayenne, for seasoning yolks',
      '150g kanpachi fillet',
      '20g sugar and 20g salt (for curing fish)',
      '50ml soy sauce and 50ml rice wine vinegar (for pickling)',
      '2 ripe avocados',
      '30g full-fat yogurt',
      '10g Dijon mustard',
      'Juice of 1 lemon',
      '2 medium Yukon Gold potatoes, finely diced brunoise',
    ],
    steps: [
      'Scramble eggs over low heat until just barely set; immediately blend with cream cheese, salt, and cayenne until smooth. Stir in dissolved gelatin. Pipe into square silicone molds; freeze solid.',
      'Season egg yolks with salt and cayenne; fill each into a small cling film cylinder, securing ends with kitchen twine. Cook in a water bath at 70°C for 17 minutes. Ice down; slice into 2.5cm cylinders.',
      'Cure kanpachi in sugar and salt 20 minutes; rinse and pickle in soy sauce and rice vinegar 10 minutes. Refrigerate until service.',
      'Blend avocado with yogurt, mustard, and lemon juice until smooth. Season. Pipe onto tray; torch surface until charred.',
      'Fry potato brunoise in neutral oil until golden and crisp; drain on paper towels.',
      'To plate: reheat scrambled egg squares gently. Place one egg square beside a yolk cylinder. Add kanpachi, charred avocado cream, and crispy potato. Serve immediately.',
    ],
    source_url: 'https://www.foodrepublic.com/2012/08/16/plate-deconstruction-wd50s-scrambled-egg-ravioli/',
    image_url: 'https://www.foodrepublic.com/img/gallery/plate-deconstruction-wd50s-scrambled-egg-ravioli/intro-import.jpg',
  },
  {
    title: 'Fried Mayonnaise',
    chef: 'Wylie Dufresne / wd~50',
    description: "Traditional oil-in-water emulsified mayonnaise is made stable at frying temperatures through the addition of gellan gum and gelatin, then chilled until firm enough to be cubed, breaded, and deep-fried into golden, crunchy bites that reveal warm, creamy, silky mayo within. The dish was considered impossible until Dufresne's collaboration with Chris Young produced the gellan breakthrough around 2006; the New York Times called it 'arguably the most talked-about single modernist dish in America.' Served as a canapé or standalone amuse-bouche, it encapsulates Dufresne's obsession with making the familiar utterly alien.",
    cuisine: 'Modernist / New American',
    difficulty: 'hard',
    prepTimeMin: 120,
    cookTimeMin: 15,
    servings: 8,
    ingredients: [
      '3 egg yolks',
      '15ml lemon juice',
      '10g Dijon mustard',
      '240ml neutral oil',
      '60ml whole milk',
      '3g gellan gum (low-acyl)',
      '4g gelatin sheets, bloomed in cold water',
      'Salt to taste',
      'Panko breadcrumbs, for breading',
      '2 eggs, beaten (for egg wash)',
      'All-purpose flour, for dredging',
      'Neutral oil, for deep frying',
    ],
    steps: [
      'Make base mayonnaise: blend egg yolks, lemon juice, and mustard; stream in oil until emulsified. Season with salt.',
      'Heat milk to 85°C; dissolve gellan gum by blending vigorously (keep above 70°C). Working quickly while above 75°C, blend hot milk-gellan mixture into the mayonnaise using an immersion blender.',
      'Squeeze excess water from bloomed gelatin and stir into the hot mixture until dissolved.',
      'Pour into a shallow container lined with cling film; refrigerate until firm (at least 2 hours).',
      'Cut into 2cm cubes. Dredge in flour, dip in egg wash, coat in panko. Refreeze 30 minutes.',
      'Deep-fry in 180°C oil for 90 seconds until golden. Transfer to a 200°C oven for 1 minute to heat through without melting.',
      'Serve immediately on tasting spoons, seasoned with fleur de sel.',
    ],
    source_url: 'https://www.foodrepublic.com/2017/10/24/deep-fry-mayonnaise-wylie-dufresne-way/',
    image_url: 'https://www.foodrepublic.com/img/gallery/deep-fry-mayonnaise-wylie-dufresne-way/intro-import.jpg',
  },
  {
    title: 'Oysters and Pearls',
    chef: 'Thomas Keller / The French Laundry',
    description: "Pearl tapioca cooked in oyster-infused milk until translucent and supple is folded with a sabayon of egg yolks and oyster liquor, crème fraîche, and whipped cream, then baked until soufflé-puffed in individual gratin dishes. Two Pacific oysters poached gently in a vermouth-shallot beurre blanc are nestled on top, and the dish is crowned with a pristine quenelle of Osetra caviar. Keller described it as representing 'the apex of American luxury ingredients.' It has appeared on The French Laundry menu continuously since the restaurant opened and is widely considered one of the most perfect dishes in American fine dining.",
    cuisine: 'New American / Modernist',
    difficulty: 'hard',
    prepTimeMin: 60,
    cookTimeMin: 20,
    servings: 4,
    ingredients: [
      '30g small pearl tapioca',
      '120ml whole milk (for soaking)',
      '8 Pacific oysters, shucked, liquor reserved',
      '150ml heavy cream',
      '30g crème fraîche',
      'Freshly cracked black pepper and salt',
      '2 egg yolks',
      '15g oyster liquor (for sabayon)',
      '60ml dry vermouth',
      '10g shallot, minced',
      '10ml white wine vinegar',
      '60g cold unsalted butter, cubed',
      '7g fresh chives, minced',
      '60g Osetra caviar',
    ],
    steps: [
      'Soak tapioca in 120ml warm milk 1 hour. Strain, discarding milk. Whip 60ml cream to soft peaks; refrigerate.',
      'Shuck oysters; separate whole bellies from frills. Simmer oyster trim with 90ml milk-cream mixture 5 minutes; strain.',
      'Add drained tapioca; cook over medium-low heat, stirring, 12–15 minutes until tapioca is tender. Fold in sabayon, crème fraîche, and whipped cream. Season.',
      'Distribute tapioca into 4 oven-safe gratin dishes; bake at 175°C until puffed, about 9 minutes.',
      'Reduce vermouth, oyster liquor, shallots, and vinegar until almost dry. Whisk in cold butter; add chives and oyster bellies, warm gently 30 seconds.',
      'Place 2 oysters on each puffed tapioca; spoon sauce around. Quenelle caviar on top using a plastic spoon.',
    ],
    source_url: 'https://parkerhallberg.com/oysters-and-pearls/',
    image_url: 'https://parkerhallberg.com/wp-content/uploads/2022/07/IMG_5899-scaled.jpeg',
  },
  {
    title: 'Melon Cantaloupe Caviar',
    chef: 'Ferran Adrià / elBulli',
    description: "The dish that introduced basic spherification to the world in 2003: fresh cantaloupe juice dropped into a calcium chloride bath forms hundreds of perfect 4mm spheres with a burst-on-the-tongue gel skin and intensely pure melon liquid inside. Adrià conceived it as a play on Osetra caviar — replacing the brine of fish roe with the sweetness of summer fruit — and served it in the same small mother-of-pearl spoon traditionally used for caviar. It became the signature dish of elBulli's 2003 season and the catalyst for the global molecular gastronomy revolution. The technique was so transformative that Adrià later dedicated an entire catalogue volume to spherification's history and applications.",
    cuisine: 'Modernist / Spanish',
    difficulty: 'hard',
    prepTimeMin: 1440,
    cookTimeMin: 20,
    servings: 8,
    ingredients: [
      '500ml fresh cantaloupe melon juice, strained',
      '2.5g sodium alginate',
      '1000ml filtered water',
      '5g calcium chloride',
      'Passion fruit pulp (optional, as original accompaniment)',
    ],
    steps: [
      'Blend sodium alginate into the melon juice using an immersion blender on high speed 1 minute until fully dissolved. Refrigerate uncovered 24 hours to remove all air bubbles.',
      'Prepare the setting bath: dissolve calcium chloride in 1000ml cold filtered water; stir well and allow to settle.',
      'Fill a squeeze bottle or syringe with the alginate melon mixture. Drop single droplets one at a time from about 3cm above the surface of the calcium bath.',
      'Allow spheres to sit in the bath exactly 60–90 seconds; the outer membrane gels while the interior stays liquid.',
      'Remove spheres with a fine slotted spoon; rinse gently in two successive baths of clean water.',
      'Store finished spheres submerged in plain melon juice until service to prevent the membrane from continuing to thicken.',
      'Serve 8–10 spheres per portion on a chilled mother-of-pearl or ceramic spoon, garnished with a drop of passion fruit pulp.',
    ],
    source_url: 'https://www.theworlds50best.com/stories/News/12-iconic-dishes-el-bulli-ferran-adria.html',
    image_url: 'https://www.finedininglovers.com/sites/default/files/article_content_images/Original_14364_Screen-Shot-2016-12-17-at-18.51.53.png',
  },
  {
    title: 'White Bean Espuma with Sea Urchin',
    chef: 'Ferran Adrià / elBulli',
    description: "The very first culinary foam ever served, debuted at elBulli in 1994: smooth white bean purée is loaded into a cream whipper charged with nitrous oxide, producing a cloud-light, intensely savory foam that retains all the body and flavor of a traditional purée but in a texture lighter than any mousse. It is presented as a snowy dollop atop a sea urchin shell — a visual pun on the contradiction of heavy versus weightless, rough versus smooth, ocean versus land. The sea urchin's iodine-sweet brininess cuts perfectly through the earthy richness of the bean. This single technique launched the ISI siphon foam that every restaurant in the world would adopt in the following decade.",
    cuisine: 'Modernist / Catalan',
    difficulty: 'hard',
    prepTimeMin: 30,
    cookTimeMin: 60,
    servings: 6,
    ingredients: [
      '300g dried white beans (cannellini), soaked overnight',
      '1 small onion, halved',
      '2 garlic cloves',
      '1 bay leaf',
      '1 sprig fresh thyme',
      '1 liter chicken or vegetable stock',
      '50ml extra virgin olive oil',
      'Salt and white pepper to taste',
      '2 N₂O chargers (for ISI whip)',
      '6 fresh sea urchin roe tongues (uni)',
      'Fleur de sel',
      'Micro herbs or chervil, to garnish',
    ],
    steps: [
      'Drain soaked beans; cover with stock, add onion, garlic, bay, and thyme. Simmer gently 60–75 minutes until very tender. Remove aromatics.',
      'Blend beans with their cooking liquid and olive oil until completely smooth and very creamy. Season generously.',
      'Pass through a fine-mesh sieve twice to ensure there are no lumps or skin fragments.',
      'While still warm, pour the purée into an ISI whip cream canister; seal. Charge with two N₂O cartridges, shaking vigorously after each. Refrigerate right-side-up at least 30 minutes.',
      'Shake canister vigorously; invert and dispense foam into sea urchin shells or small ceramic bowls in long, soft strokes.',
      'Lay a tongue of fresh sea urchin roe on top of the foam. Finish with a pinch of fleur de sel and micro herbs.',
      'Serve immediately — the foam will begin to deflate within 3–4 minutes.',
    ],
    source_url: 'https://www.tastingtable.com/1083892/the-first-dish-to-feature-el-bullis-game-changing-foam/',
    image_url: 'https://www.tastingtable.com/img/gallery/the-first-dish-to-feature-el-bullis-game-changing-foam/l-intro-1667467852.jpg',
  },
  {
    title: 'Edible Stones (Kaolin-Coated Potatoes)',
    chef: 'Andoni Luis Aduriz / Mugaritz',
    description: "Small Chérie potatoes are boiled in salted water, then triple-dipped in a coating of food-grade kaolin clay, lactose, black vegetable coloring, and salt dissolved in water — calibrated over 13 test batches to achieve a coating that dries into a convincingly stone-like texture that is edible but flavorless. The potatoes are then arranged among actual river stones on a slate board and presented without explanation; diners must discover for themselves which are edible, biting into something they believe is inedible and finding a warm, creamy, perfectly cooked potato within. The dish was inspired by Andean tuntas — naturally freeze-dried potatoes — and is one of the most provocative acts of culinary trompe l'oeil in contemporary gastronomy.",
    cuisine: 'Modernist / Spanish Basque',
    difficulty: 'hard',
    prepTimeMin: 90,
    cookTimeMin: 35,
    servings: 4,
    ingredients: [
      '16 small Chérie potatoes',
      '3 liters water',
      '24g salt',
      '60ml food-grade kaolin clay',
      '40g lactose',
      '1g black vegetable coloring',
      '80ml water (for coating)',
      '40g garlic confit (1 head garlic slow-cooked in 500ml olive oil 2 hours)',
      '1 egg yolk',
      '60ml extra virgin olive oil',
      'Salt to taste (for aioli)',
    ],
    steps: [
      'Make garlic confit: warm olive oil to 80°C, add unpeeled garlic cloves, simmer 2 hours until soft. Drain, peel, and pass through a fine sieve.',
      'Boil potatoes in salted water 15–20 minutes until just tender. Drain and cool slightly.',
      'Prepare coating: combine kaolin, lactose, black coloring, and salt. Gradually whisk in 80ml water. Rest 1 hour until smooth.',
      'Insert wooden skewers into each potato. Dip completely in coating; insert skewered end into holes of a perforated baking tray to hold upright.',
      'Bake at 50°C for 30 minutes until coating is completely dry and stone-like.',
      'Make aioli: blend garlic confit and egg yolk; gradually stream in olive oil until emulsified. Season.',
      'Heat potatoes to 70°C. Arrange among actual river stones on a slate. Serve with aioli; offer no explanation.',
    ],
    source_url: 'https://reportergourmet.com/en/news/5896-the-edible-stones-that-stunned-the-world-mugaritz-s-recipe',
    image_url: 'https://reportergourmet.com/upload/news/5896/copertina-sassi-edibili-mugaritz.jpg',
  },
  {
    title: 'Carbonated Mojito Spheres',
    chef: 'José Andrés / Minibar',
    description: "A fully composed mojito — white rum, fresh lime juice, mint, and sugar — is formed into large spheres via reverse spherification in a sodium alginate bath, then carbonated in a CO₂-charged siphon over two hours so the liquid inside becomes effervescent. Each sphere bursts on the palate with a cold, boozy, carbonated mojito explosion. It is simultaneously a cocktail, a canapé, and a magic trick, exemplifying Andrés's Minibar philosophy of compressing an entire beverage experience into a single, intensely sensory bite.",
    cuisine: 'Modernist / Spanish-American',
    difficulty: 'hard',
    prepTimeMin: 1440,
    cookTimeMin: 15,
    servings: 8,
    ingredients: [
      '20 fresh mint leaves',
      '350g fresh lime juice',
      '350g white rum',
      '250g distilled water',
      '12 tablespoons sugar',
      '11.2g calcium lactate gluconate',
      '1.6g xanthan gum',
      '5g sodium alginate',
      '1000g distilled water (for alginate bath)',
      'Miniature mint leaves, to garnish',
      'Lime zest, to garnish',
    ],
    steps: [
      'Blend sodium alginate into 1000g distilled water; refrigerate uncovered 24 hours to degas.',
      'Muddle lime juice, water, and mint 1 minute; strain. Add sugar and rum; stir until dissolved. Reserve 200g of this plain mojito for storage.',
      'Weigh 350g of the mojito into a separate container; add calcium lactate gluconate and blend thoroughly. Add xanthan gum and blend again. Refrigerate 1–24 hours to release air.',
      'Pour sodium alginate bath into a wide flat container. Using a tablespoon, scoop mojito mixture and lower gently onto the surface; allow to form 4cm spheres for 5 minutes.',
      'Remove spheres with a slotted spoon; rinse in two clean water baths.',
      'Transfer spheres and reserved plain mojito into an ISI whip canister (less than half full); charge with a CO₂ cartridge. Rest 2 hours in refrigerator.',
      'Discharge pressure carefully; plate spheres on tasting spoons. Garnish with micro mint leaf and lime zest; serve immediately.',
    ],
    source_url: 'https://www.modernistcookingathome.com/mojito-spheres/',
    image_url: 'https://www.modernistcookingathome.com/wp-content/uploads/mojito-spheres.jpg',
  },
  {
    title: 'Gin & Tonic with Cucumber Spheres',
    chef: 'Grant Achatz / The Aviary',
    description: "A reimagined Gin & Tonic in which the cucumber element — typically a garnish — becomes the entire visual and textural spectacle: hundreds of 8mm spheres of cucumber juice formed by reverse spherification fill a tall glass before the separately prepared carbonated gin-and-Chartreuse base is poured over. Each sip delivers a cloud of cucumber spheres that burst one by one, dispensing fresh cucumber liquid into the cocktail. One of the most celebrated drinks in the Aviary Cocktail Book, it showcases how molecular technique can elevate a classic to the level of experiential performance.",
    cuisine: 'Modernist / American',
    difficulty: 'hard',
    prepTimeMin: 1440,
    cookTimeMin: 30,
    servings: 4,
    ingredients: [
      '4 large cucumbers',
      '108g sugar',
      '20g calcium lactate',
      '6g kosher salt',
      '7.5g sodium alginate',
      '1000g filtered water (for alginate bath)',
      '60ml Junipero gin',
      '15ml green Chartreuse',
      '15ml simple syrup',
      '1.3g citric acid',
      '120ml Fever Tree Indian tonic water',
    ],
    steps: [
      'Blend sodium alginate into 1000g filtered water; refrigerate uncovered 24 hours to fully hydrate and degas.',
      'Juice cucumbers and strain. Blend 700g cucumber juice with sugar, calcium lactate, and salt until fully dissolved.',
      'Fill hemispheric silicone molds (8mm) with the mixture using a syringe. Freeze completely solid.',
      'Warm the alginate bath to 25°C. Drop frozen hemispheres in pairs into the bath; allow to melt and form spheres over 4–5 minutes.',
      'Remove finished spheres with a spherification spoon; rinse in two successive clean water baths. Store in reserved plain cucumber juice.',
      'Make cocktail: combine gin, Chartreuse, simple syrup, citric acid, and tonic without ice; stir gently. Refrigerate until very cold.',
      'Place approximately 100 cucumber spheres in a chilled tall glass with a straw. Carbonate cocktail base in a soda siphon; pour gently over spheres. Serve immediately.',
    ],
    source_url: 'https://capitalcocktails.com/2021/01/08/molecular-cocktail-recipe-the-aviary-gin-tonic/',
    image_url: 'https://i0.wp.com/capitalcocktails.com/wp-content/uploads/2021/01/Aviarys-Gin-Tonic.jpg?fit=900%2C1125&ssl=1',
  },
];

const checkExists = db.prepare('SELECT id FROM recipes WHERE title = ?');
const insertRecipe = db.prepare(`
  INSERT INTO recipes (id, title, description, cuisine, difficulty, prep_time_min, cook_time_min, servings, tags, source_url, created_at, updated_at)
  VALUES (?, ?, ?, ?, ?, ?, ?, ?, NULL, ?, ?, ?)
`);
const insertIngredient = db.prepare(`
  INSERT INTO recipe_ingredients (id, recipe_id, name_override, step_order)
  VALUES (?, ?, ?, ?)
`);
const insertStep = db.prepare(`
  INSERT INTO recipe_steps (id, recipe_id, step_number, instruction)
  VALUES (?, ?, ?, ?)
`);
const insertMedia = db.prepare(`
  INSERT INTO recipe_media (id, recipe_id, type, url_or_path, caption, is_primary, sort_order)
  VALUES (?, ?, 'image', ?, 'Primary recipe photo', 1, 0)
`);

const insertAll = db.transaction((recipes: Recipe[]) => {
  let inserted = 0;
  for (const r of recipes) {
    const existing = checkExists.get(r.title);
    if (existing) {
      console.log(`  ⏭  Skipping (exists): ${r.title}`);
      continue;
    }
    const id = ulid();
    const ts = now();
    insertRecipe.run(id, r.title, r.description, r.cuisine, r.difficulty, r.prepTimeMin, r.cookTimeMin, r.servings, r.source_url, ts, ts);
    r.ingredients.forEach((name, i) => insertIngredient.run(ulid(), id, name, i));
    r.steps.forEach((instruction, i) => insertStep.run(ulid(), id, i + 1, instruction));
    if (r.image_url) insertMedia.run(ulid(), id, r.image_url);
    console.log(`  ✅ Inserted: ${r.title}`);
    inserted++;
  }
  return inserted;
});

const count = insertAll(RECIPES);
console.log(`\nDone — ${count} new recipes added.`);
