#!/usr/bin/env tsx
/**
 * Seed 21 modernist / spectacular entrée recipes.
 * Safe to re-run — skips existing titles.
 */
import Database from 'better-sqlite3';
import path from 'path';
import { ulid } from 'ulid';

const DB_PATH = path.join(process.cwd(), 'chew.db');
const db = new Database(DB_PATH);
const now = () => Math.floor(Date.now() / 1000);

type Recipe = {
  title: string;
  chef: string;
  description: string;
  cuisine: string;
  difficulty: 'easy' | 'medium' | 'hard';
  prepTimeMin: number;
  cookTimeMin: number;
  servings: number;
  ingredients: string[];
  steps: string[];
  source_url: string | null;
  image_url: string | null;
};

const RECIPES: Recipe[] = [
  {
    title: `Beef Wellington`,
    chef: `Gordon Ramsay`,
    description: `A prime centre-cut beef fillet is seared to a deep mahogany crust, coated in English mustard, then wrapped in a fine duxelles of wild mushrooms and Parma ham before being encased in golden puff pastry. The result is a dramatic cross-section of perfectly pink beef surrounded by umami-rich mushroom paste and shatteringly crisp pastry. Ramsay's version is considered the definitive modern reference for this British classic.`,
    cuisine: `British`,
    difficulty: `hard`,
    prepTimeMin: 60,
    cookTimeMin: 45,
    servings: 4,
    ingredients: [
      `750g centre-cut beef fillet, trimmed`,
      `2 tbsp English mustard`,
      `500g mixed wild mushrooms (chestnut, porcini, shiitake), finely chopped`,
      `2 shallots, finely minced`,
      `3 cloves garlic, minced`,
      `50ml dry Madeira wine`,
      `8 slices Parma ham`,
      `500g all-butter puff pastry`,
      `2 egg yolks, beaten with 1 tsp water`,
      `Fleur de sel and cracked black pepper`,
      `2 tbsp unsalted butter`,
      `1 tbsp olive oil`,
      `1 sprig fresh thyme`,
    ],
    steps: [
      `Season the beef fillet generously all over with fleur de sel and cracked black pepper. Heat a cast-iron skillet over the highest possible heat until smoking. Add olive oil and sear the beef on all sides for 2–3 minutes total — you want deep colour without cooking the interior. Remove and brush immediately and generously with English mustard while hot. Allow to cool completely on a wire rack.`,
      `For the duxelles: heat butter in a wide sauté pan over high heat. Add shallots and garlic, sweat 2 minutes. Add all mushrooms in a single addition — they will release moisture. Cook, stirring frequently, until all liquid has evaporated and the mixture is completely dry, dark, and paste-like, about 18 minutes. Deglaze with Madeira, cook dry. Season well, spread onto a sheet tray and refrigerate until cold.`,
      `Lay a large sheet of cling film on your work surface. Arrange Parma ham slices in overlapping rows forming a rectangle large enough to wrap the beef. Spread the cold duxelles evenly over the ham to a 3mm thickness. Place the seared, mustard-coated fillet at the near edge and roll tightly using the cling film to form a tight cylinder. Twist the ends to compress and refrigerate for at least 30 minutes.`,
      `On a lightly floured surface, roll out the puff pastry to a rectangle 3mm thick. Remove the cling film from the beef roll and place it at the near edge of the pastry. Brush the far pastry edge with egg wash. Roll tightly, seal the seam underneath, and crimp the ends. Brush the entire surface with egg wash. Score a crosshatch pattern with the back of a knife, taking care not to cut through the pastry. Chill the assembled Wellington for 20 minutes.`,
      `Preheat the oven to 220°C (200°C fan). Place the Wellington seam-side down on a baking tray lined with parchment. Bake for 20 minutes until deeply golden, then reduce to 180°C and bake a further 15 minutes. Use a probe thermometer to check the internal temperature: 52°C for rare, 57°C for medium-rare. Rest uncovered for 10–12 minutes before slicing with a sharp carving knife. Serve with a rich Madeira jus.`,
    ],
    source_url: 'http://www.goodtoknow.co.uk/recipes/164868/Gordon-Ramsay-s-beef-Wellington',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Beef_Wellington_%E5%88%87%E9%9D%A2.jpg/900px-Beef_Wellington_%E5%88%87%E9%9D%A2.jpg',
  },
  {
    title: `Duck Confit with Sarladaise Potatoes`,
    chef: `Thomas Keller / French Laundry tradition`,
    description: `Duck legs are cured overnight in a aromatic salt mixture, then submerged and slow-cooked in their own rendered fat at a precise low temperature until the collagen melts to silk and the meat achieves extraordinary tenderness. The legs are then crisped under a blazing salamander to achieve lacquer-thin crackling skin. Served alongside potatoes cooked in duck fat with garlic and thyme in the Périgord style.`,
    cuisine: `French`,
    difficulty: `hard`,
    prepTimeMin: 1440,
    cookTimeMin: 180,
    servings: 4,
    ingredients: [
      `4 duck legs (Moulard preferred)`,
      `30g kosher salt`,
      `1 tbsp cracked black pepper`,
      `4 cloves garlic, crushed`,
      `4 sprigs fresh thyme`,
      `2 bay leaves, crumbled`,
      `1 tsp sugar`,
      `1kg rendered duck fat (or enough to submerge legs)`,
      `800g waxy potatoes (Charlotte or fingerling), sliced 3mm thick`,
      `4 cloves garlic, thinly sliced`,
      `2 sprigs fresh thyme`,
      `200ml duck fat (reserved from confit)`,
      `Fleur de sel, to finish`,
      `Fresh flat-leaf parsley, finely chopped`,
    ],
    steps: [
      `Combine salt, pepper, sugar, crushed garlic, thyme, and crumbled bay leaves in a bowl. Rub the cure mixture thoroughly into every surface of the duck legs, including under the skin where possible. Lay in a single layer in a glass or ceramic dish, cover tightly, and refrigerate for 24 hours. The cure will draw out moisture and flavour the meat deeply.`,
      `Rinse the duck legs thoroughly under cold water to remove all cure, then pat completely dry with paper towels — any moisture will cause the fat to spit. Melt the duck fat in a deep, heavy-bottomed pot or Dutch oven over very low heat until clear and approximately 82°C (180°F). Submerge the duck legs fully — they must be completely covered. Maintain this temperature for 2.5–3 hours, adjusting heat as needed. The fat should barely tremble, never bubble.`,
      `Gently remove the duck legs with a spider or slotted spoon. They can be stored submerged in the fat in the refrigerator for up to 2 weeks at this stage — the fat is a preservative. Before serving, bring to room temperature for 30 minutes.`,
      `For the sarladaise: heat duck fat in a heavy oven-safe skillet over medium heat. Layer potatoes, sliced garlic, and thyme in shingled rows, seasoning between each layer. Cook on the stovetop 10 minutes, pressing down with a spatula, then transfer to a 180°C oven for 35–40 minutes until golden and crisp on the bottom and cooked through. Invert onto a plate.`,
      `To finish the duck: preheat a grill or salamander to the maximum setting. Place the duck legs skin-side up on a wire rack set over a tray. Blast with high heat for 4–6 minutes until the skin is lacquered, blistered, and deeply crisp. Season with a pinch of fleur de sel. Serve immediately on the sarladaise potatoes.`,
    ],
    source_url: 'https://www.bbcgoodfood.com/recipes/2085/barneys-confit-of-duck',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Duck_confit_p%C3%A2t%C3%A9_salad.jpg/900px-Duck_confit_p%C3%A2t%C3%A9_salad.jpg',
  },
  {
    title: `Five Ages of Parmigiano Reggiano in Different Textures and Temperatures`,
    chef: `Massimo Bottura — Osteria Francescana`,
    description: `Massimo Bottura's most celebrated dish transforms a single ingredient — Parmigiano Reggiano — across five preparations: a 24-month soufflé, a 30-month crispy wafer, a 36-month foam, a 40-month cream, and a 50-month gelatin. Each expression reveals a different dimension of the cheese's terroir and aging process, arranged on the plate as an edible meditation on time and place. The dish is the defining statement of Bottura's philosophy that Italian cuisine must look forward.`,
    cuisine: `Italian (Modernist)`,
    difficulty: `hard`,
    prepTimeMin: 120,
    cookTimeMin: 90,
    servings: 4,
    ingredients: [
      `200g Parmigiano Reggiano 24-month, finely grated (for soufflé base)`,
      `200g Parmigiano Reggiano 30-month, finely grated (for crispy wafers)`,
      `200g Parmigiano Reggiano 36-month, rind reserved (for foam)`,
      `200g Parmigiano Reggiano 40-month (for cream)`,
      `150g Parmigiano Reggiano 50-month (for gelatin)`,
      `500ml whole milk`,
      `250ml heavy cream`,
      `4 eggs, separated`,
      `2g soy lecithin (for foam)`,
      `2g agar-agar (for gelatin)`,
      `2g xanthan gum`,
      `50g unsalted butter`,
      `30g all-purpose flour`,
      `Salt, white pepper, and freshly grated nutmeg`,
      `Aged balsamic vinegar tradizionale, for serving`,
    ],
    steps: [
      `For the 50-month gelatin: dissolve agar-agar in 250ml of Parmigiano 50-month broth (simmer rind and grated cheese in water, strain) over medium heat. Season, pour into a shallow tray to a depth of 5mm, and refrigerate until set. Cut into precise 2cm squares and reserve cold.`,
      `For the 40-month cream: combine 100ml heavy cream with finely grated 40-month Parmigiano in a bain-marie, whisking gently until melted and homogenous. Season with white pepper and nutmeg. Pass through a fine sieve. Transfer to a squeeze bottle, keep warm at 60°C.`,
      `For the 36-month foam: warm 200ml of Parmigiano broth (made from 36-month rinds), season, and add soy lecithin. Using an immersion blender held at a 45-degree angle at the surface of the liquid, whip into a fine, dry foam. Work to order.`,
      `For the 30-month crispy wafers: finely grate the 30-month Parmigiano. Spread in thin rounds on a Silpat-lined tray. Bake at 180°C for 6–8 minutes until golden and lacy. Remove carefully and drape over a curved mould immediately to set in a curved shape. Reserve at room temperature.`,
      `For the 24-month soufflé: make a classic béchamel with butter, flour, and milk. Remove from heat, stir in finely grated 24-month Parmigiano until melted. Fold in beaten egg yolks, then fold in stiff egg whites. Fill buttered ramekins to 80% capacity and bake in a bain-marie at 190°C for 12–14 minutes until risen and set. To plate: place the warm soufflé ramekin at the center, arrange the gelatin square, a quenelle of warm cream, the lacy wafer, and a cloud of fresh foam in a composed arc around it. Finish with 3 drops of aged balsamic tradizionale.`,
    ],
    source_url: 'https://www.theguardian.com/lifeandstyle/2014/oct/11/massimo-bottura-five-ages-of-parmigiano-reggiano-recipe',
    image_url: null,
  },
  {
    title: `Slow-Poached Salmon in a Cucumber Consommé`,
    chef: `Thomas Keller — The French Laundry`,
    description: `A technique-driven preparation in which a thick salmon medallion is slow-poached in barely simmering clarified butter at 57°C, yielding a texture of unparalleled silkiness that falls apart in thin, glassy layers. The dish is served in a pool of intensely flavoured, crystal-clear cucumber consommé made by the freeze-clarification method, finished with dill oil and a scattering of cucumber pearls made by melon baller. The combination of warm fish and chilled consommé creates a startling temperature contrast.`,
    cuisine: `French-American`,
    difficulty: `hard`,
    prepTimeMin: 60,
    cookTimeMin: 40,
    servings: 4,
    ingredients: [
      `4 portions wild king salmon, 120g each, skin removed, cut into cylinders`,
      `500g clarified butter`,
      `2 large English cucumbers, juiced`,
      `1 cup cold cucumber juice (for consommé)`,
      `2 egg whites`,
      `1 tbsp champagne vinegar`,
      `Fresh dill, 1 bunch`,
      `100ml grapeseed oil (for dill oil)`,
      `1 small cucumber, for pearls (melon baller)`,
      `Fleur de sel`,
      `White pepper`,
      `2 sprigs tarragon`,
    ],
    steps: [
      `For the consommé: juice the cucumbers in a cold-press juicer. Combine the juice with lightly beaten egg whites and bring slowly to 65°C, stirring constantly. Stop stirring as a raft forms. Simmer 20 minutes. Alternatively, for the freeze-clarification method, freeze the cucumber juice solid, then allow it to drip through a muslin-lined strainer in the refrigerator for 12 hours. The resulting liquid is brilliantly clear. Season with champagne vinegar, salt, and white pepper. Chill.`,
      `For the dill oil: blanch dill fronds in boiling salted water for 10 seconds, then shock in ice water. Squeeze dry and blend at high speed with cold grapeseed oil for 3 minutes. Strain through muslin and refrigerate. The oil should be a vivid, stable green.`,
      `For cucumber pearls: using a small Parisian scoop or melon baller, cut precisely spherical pearls from the cucumber flesh, avoiding seeds. Place in ice water to firm.`,
      `For the salmon: heat clarified butter in a deep, wide saucepan over extremely gentle heat to exactly 57°C. Use a thermometer — precision is critical. Gently lower the salmon cylinders into the butter and poach for 14–16 minutes, maintaining the temperature within 1°C. The salmon will turn from translucent to opaque but remain deeply silky and yielding.`,
      `To plate: ladle 60ml of cold cucumber consommé into a wide, shallow warmed bowl. Lift the salmon gently with a fish spatula and place it at the center. Arrange cucumber pearls in a precise cluster beside the fish. Drizzle a thin thread of dill oil around the consommé. Place one perfect dill frond on the salmon. Add a pinch of fleur de sel immediately before service.`,
    ],
    source_url: 'https://www.foodandwine.com/recipes/slow-poached-salmon-cucumber-vinaigrette',
    image_url: null,
  },
  {
    title: `Beef Bourguignon Reimagined`,
    chef: `Daniel Humm — Eleven Madison Park`,
    description: `A modernist deconstruction of the Burgundian classic in which beef cheeks are braised for 12 hours in Gevrey-Chambertin until every fibre surrenders, then pressed overnight and cut into perfect cubes, seared to a mahogany glaze. The braising liquid is reduced to a trembling, lacquer-bright jus, and the garnishes — pearl onions, lardons, and button mushrooms — are each treated as separate jewels with perfect individual texture. The plate arrives looking like a composed painting rather than a stew.`,
    cuisine: `French (Modernist)`,
    difficulty: `hard`,
    prepTimeMin: 60,
    cookTimeMin: 720,
    servings: 4,
    ingredients: [
      `2 whole beef cheeks (about 1.2kg total), trimmed of sinew`,
      `1 bottle Gevrey-Chambertin or good Burgundy`,
      `500ml brown chicken jus`,
      `200g thick-cut lardons`,
      `200g pearl onions, peeled`,
      `300g button mushrooms, cleaned`,
      `3 medium carrots, roughly chopped`,
      `2 stalks celery, roughly chopped`,
      `1 head garlic, halved horizontally`,
      `2 tbsp tomato paste`,
      `3 sprigs thyme, 2 bay leaves`,
      `50g unsalted butter`,
      `1 tbsp grapeseed oil`,
      `Salt and black pepper`,
      `Fresh flat-leaf parsley leaves, to garnish`,
    ],
    steps: [
      `The day before: season beef cheeks aggressively with salt and pepper. Sear in grapeseed oil in a heavy rondeau over high heat until deeply caramelised on all sides, about 8 minutes. Remove. In the same pan, cook carrots, celery, and garlic cut-side down until deeply coloured. Add tomato paste and cook, stirring, for 2 minutes. Deglaze with the entire bottle of wine. Return the beef cheeks, add the chicken jus and herbs, and bring to a bare simmer. Cover with a cartouche and a lid, then braise in a 150°C oven for 4–5 hours until completely tender.`,
      `Remove the cheeks and strain the braising liquid through a fine chinois, pressing the vegetables well. Return the liquid to a saucepan and reduce by two-thirds to a rich, glossy jus. Taste and adjust seasoning. Place the warm cheeks in a terrine mould lined with cling film, pour over just enough reduced jus to fill gaps, fold the cling film over the top, and press under heavy weights overnight in the refrigerator.`,
      `For the garnish: blanch pearl onions in boiling salted water for 2 minutes, cool, and peel. Glaze in a sauté pan with butter and a pinch of sugar until golden and tender, about 8 minutes. Separately, render the lardons until crisp and golden. Quarter the mushrooms and sauté in butter over high heat until golden. Season all garnishes separately and keep warm.`,
      `To serve: unmould the pressed cheek terrine and cut into 5cm cubes. Season and sear on all sides in a hot pan with clarified butter until glazed and hot through. Brush generously with the warm reduced jus.`,
      `Compose the plate: place a beef cheek cube at the centre. Arrange 3 pearl onions, a cluster of mushrooms, and a tangle of lardons around it. Spoon the glossy jus over and around. Dot with tiny parsley leaves. The dish should look architectural and precise.`,
    ],
    source_url: 'https://www.bbcgoodfood.com/recipes/5032/beef-bourguignon',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Boeuf_Bourguignon.jpg/900px-Boeuf_Bourguignon.jpg',
  },
  {
    title: `Whole Roasted Cauliflower with Black Truffle`,
    chef: `Daniel Humm — Eleven Madison Park`,
    description: `A head of cauliflower is slow-roasted whole over several hours, basted repeatedly in cultured butter and honey until it transforms into a deeply caramelised, nutty centrepiece that commands the same reverence as a roast of meat. It is then carved tableside and served with a black truffle purée, preserved lemon, and a scattering of toasted pine nuts and golden raisins in the Sicilian agrodolce tradition. The dish proved transformative for plant-forward fine dining.`,
    cuisine: `American (Modernist)`,
    difficulty: `hard`,
    prepTimeMin: 30,
    cookTimeMin: 150,
    servings: 4,
    ingredients: [
      `1 large head white cauliflower, leaves trimmed`,
      `150g cultured unsalted butter`,
      `3 tbsp wildflower honey`,
      `1 tbsp sherry vinegar`,
      `50g black truffle, finely grated plus sliced for garnish`,
      `300g cauliflower florets (extra, for purée)`,
      `200ml whole milk`,
      `100g pine nuts, toasted`,
      `60g golden raisins, plumped in warm water`,
      `1 preserved lemon, rind only, finely minced`,
      `Fleur de sel`,
      `Fresh thyme, 4 sprigs`,
      `50ml grapeseed oil`,
    ],
    steps: [
      `Preheat oven to 180°C. Blanch the whole cauliflower head in well-salted boiling water for 6 minutes, then lift out and drain well upside down on a rack. This begins the cooking and ensures the core becomes tender.`,
      `In a small saucepan, melt butter with honey and sherry vinegar. Season with salt. Place the cauliflower, core-side down, in a snug oven-safe skillet or baking dish. Pour over half the butter glaze and roast for 40 minutes, basting with accumulated pan juices every 10 minutes. Increase oven to 200°C and continue to roast, basting now with the remaining fresh glaze every 10 minutes, for another 50–60 minutes. The exterior should be a deep, even amber with concentrated caramelisation.`,
      `For the truffle–cauliflower purée: cook extra cauliflower florets in whole milk with a pinch of salt until completely tender. Drain, reserving the milk. Blend in a high-speed blender with enough warm milk to achieve a very smooth, silky consistency. Pass through a fine tamis. Fold in half the grated truffle, adjust seasoning, and keep warm.`,
      `For the agrodolce garnish: in a small sauté pan, warm a little butter. Add toasted pine nuts, plumped raisins, minced preserved lemon rind, and remaining grated truffle. Toss gently, season, and warm through.`,
      `To serve: spread a generous swoosh of truffle-cauliflower purée across the plate. Set the whole roasted cauliflower (or carved into four sections) onto the purée. Spoon the pine nut agrodolce over and around. Garnish with thin truffle slices. Finish with fleur de sel and a drizzle of the pan glaze.`,
    ],
    source_url: 'https://www.foodandwine.com/vegetables/cauliflower/whole-roasted-cauliflower-recipes',
    image_url: null,
  },
  {
    title: `Lamb with Cucumber, Dill, and Nasturtium`,
    chef: `Grant Achatz — Alinea`,
    description: `An Alinea course in which a precisely cooked lamb loin is served in a fleeting composition with cucumber compressed in elderflower, fresh dill flowers, and nasturtium petals arranged so that the plate looks like a moment frozen from a forest floor. The lamb is cooked sous vide for 45 minutes at 58°C, chilled in an ice bath, then seared in clarified butter for fifteen seconds per side to create a caramelised exterior of almost microscopic thinness. The contrast between savagery and delicacy defines the dish.`,
    cuisine: `American (Modernist)`,
    difficulty: `hard`,
    prepTimeMin: 90,
    cookTimeMin: 60,
    servings: 4,
    ingredients: [
      `600g lamb loin, trimmed of all sinew and silver skin`,
      `4 portions English cucumber, cut in 7cm cylinders`,
      `100ml elderflower cordial`,
      `100ml water`,
      `1 bunch fresh dill, fronds picked`,
      `20 nasturtium petals and leaves, small`,
      `200ml lamb jus (from roasted bones)`,
      `2g agar-agar`,
      `100ml cucumber juice (for gel)`,
      `Clarified butter for searing`,
      `Fleur de sel`,
      `Cracked black pepper`,
      `Dill oil (blanched dill blended with grapeseed oil, strained)`,
    ],
    steps: [
      `Season the lamb loin with salt and white pepper. Seal in a vacuum bag with a small knob of butter and a sprig of dill. Cook sous vide at 58°C for 45 minutes for medium-rare. Remove from water bath and rest in the sealed bag for 10 minutes. When ready to serve, cut the bag open, pat the loin dry with paper towels.`,
      `Compress the cucumber: peel and cut cylinders. Combine elderflower cordial and water. Place cucumber and liquid in a vacuum bag and seal on full compression twice. Allow to rest 15 minutes — the cucumber will take on the floral, translucent quality of the compression liquid. Slice into 4mm rounds.`,
      `For the cucumber gel: heat cucumber juice with agar-agar to dissolve completely. Pour onto a flat tray to a depth of 2mm and refrigerate until set. Cut into precise small squares or use a pastry cutter to make rounds. Reserve cold.`,
      `Reduce the lamb jus by half to a glossy, full-bodied consistency. Season and keep warm. Prepare all garnish elements — dill fronds, nasturtium petals and leaves — in ice water to keep crisp and vivid.`,
      `To finish: heat clarified butter in a very hot pan until shimmering. Sear the lamb loin for 15 seconds on each of its four sides — the goal is colour only, not additional cooking. Slice into 4 portions with a very sharp knife. Plate: paint a fine line of dill oil across the plate. Arrange compressed cucumber rounds and cucumber gel pieces. Place the lamb. Dress with warm lamb jus. Scatter nasturtium and dill flowers. Serve immediately.`,
    ],
    source_url: 'https://www.granthachatz.com/recipes',
    image_url: null,
  },
  {
    title: `Sound of the Sea`,
    chef: `Heston Blumenthal — The Fat Duck`,
    description: `One of Heston Blumenthal's most theatrical dishes, 'Sound of the Sea' is a composed seafood plate designed to transport the diner to a beach: an edible sea-foam of oyster and seaweed, raw langoustine and abalone arranged on a base of tapioca 'sand' with crushed violet potato, powdered seaweed and fried baby eels. Diners are given an iPod in a conch shell playing sounds of crashing waves and seagulls to eat alongside, proving that sound dramatically alters the perception of flavour — a principle backed by experimental psychology.`,
    cuisine: `British (Modernist)`,
    difficulty: `hard`,
    prepTimeMin: 180,
    cookTimeMin: 60,
    servings: 4,
    ingredients: [
      `8 langoustines, shells removed, tail meat reserved`,
      `200g abalone or surf clam, thinly sliced`,
      `100g baby eels (angulas), fried in oil`,
      `150g tapioca pearls (large)`,
      `4g soy lecithin`,
      `300ml oyster water (from freshly shucked oysters)`,
      `50g dried wakame and nori seaweed, powdered`,
      `6 oysters, freshly shucked`,
      `100g purple/violet potato, cooked and broken into fine crumbs`,
      `50ml grapeseed oil infused with seaweed`,
      `Sea lettuce (ulva lactuca) for garnish`,
      `50g edamame beans, blanched`,
      `Sea purslane and samphire for garnish`,
      `Shaved bonito (katsuobushi) for garnish`,
    ],
    steps: [
      `For the tapioca sand: cook large tapioca pearls in boiling salted water until just transparent. Drain thoroughly and spread in a thin layer on a Silpat-lined tray. Dry in a 70°C oven for 4–6 hours until completely desiccated and hard. Deep-fry in batches in 190°C oil for 3–4 seconds until they puff and expand. Drain, cool, and grind to a coarse, sand-like consistency. Mix with powdered seaweed and fine crumbs of cooked violet potato to create a coloured, textured 'beach sand.'`,
      `For the sea foam: combine oyster water with a small amount of seaweed stock. Season carefully. Add 4g soy lecithin per 500ml of liquid. Using an immersion blender held at the surface of the liquid at a 45-degree angle, whip vigorously to create a dry, stable, sea-foam. This technique produces a foam that holds for several minutes without collapsing.`,
      `Prepare the garnish: blanch sea lettuce, samphire, and purslane for 30 seconds. Shock in ice water. Gently fry the angulas in a little seaweed-infused oil for 20 seconds until just set. Keep warm.`,
      `Dress the langoustine and abalone: season lightly with fine sea salt. If langoustine is live-sashimi quality, leave entirely raw. Otherwise, warm the langoustine briefly (30 seconds) in warm seaweed-infused oil at 55°C. Slice the abalone paper-thin.`,
      `To plate: using a rectangular slate or shallow bowl, lay down a layer of 'tapioca sand' in the lower two-thirds, creating a beach-like gradient. Arrange langoustine, abalone, angulas, edamame, and sea vegetables on and in the sand. Spoon the oyster and seaweed foam in a wave along the upper edge. Add shaved bonito to 'blow' in the air above. Serve with the conch shell containing the iPod playing coastal soundscape.`,
    ],
    source_url: 'https://www.thefatduck.co.uk/the-fat-duck/the-menu',
    image_url: null,
  },
  {
    title: `Pheasant, Shallot, Cider, and Black Truffle`,
    chef: `Grant Achatz — Alinea`,
    description: `A complex Alinea composition presenting pheasant in multiple preparations — a sous vide breast, a crisped leg confit, and a thin slice of pheasant ballotine — alongside caramelised shallots that have been slow-cooked in cider until jammy and translucent, finished with shavings of Périgord black truffle. The whole is bound by a cider and game bird jus reduction perfumed with apple blossom vinegar. The dish reflects Achatz's view that fine dining's purpose is to make the familiar strange.`,
    cuisine: `American (Modernist)`,
    difficulty: `hard`,
    prepTimeMin: 120,
    cookTimeMin: 90,
    servings: 4,
    ingredients: [
      `2 whole pheasants, broken down (breasts, legs, carcasses reserved for jus)`,
      `6 medium banana shallots, peeled`,
      `400ml dry farmhouse cider`,
      `1 medium black truffle (Périgord), approximately 30g`,
      `Pheasant carcasses and wings, for jus`,
      `300ml brown chicken stock`,
      `2 tbsp apple blossom or cider vinegar`,
      `50g unsalted butter`,
      `1 tsp sugar`,
      `Thyme, bay leaf, for jus aromatics`,
      `Vacuum bags and sous vide equipment`,
      `Grapeseed oil for searing`,
      `Fleur de sel, white pepper`,
    ],
    steps: [
      `For the pheasant jus: roast carcasses and wings at 220°C until deeply browned, about 25 minutes. Transfer to a stockpot with thyme, bay, and stock. Simmer 90 minutes. Strain, return to pan, and reduce to approximately 150ml. Deglaze the roasting pan with cider and add to the jus. Reduce further to a glossy, trembling consistency. Finish with a splash of apple blossom vinegar and cold butter, mounting the sauce off heat.`,
      `For the cider-braised shallots: halve shallots lengthwise and cook cut-side down in butter and sugar over medium heat until deeply caramelised, about 15 minutes. Add 200ml cider, season, and braise gently until the liquid is almost entirely absorbed and shallots are jammy, translucent, and intensely sweet, about 25 minutes more.`,
      `Cure pheasant breasts with salt, white pepper, and thyme for 2 hours refrigerated. Vacuum seal with a knob of butter. Cook sous vide at 61°C for 35 minutes for a gently cooked, silky texture. Chill in ice bath. Confit the legs in duck fat at 82°C for 1.5 hours until tender. Pick the leg meat and press into a small cylinder mould. Refrigerate until firm, then slice and crisp in butter.`,
      `Remove pheasant breasts from bag, pat dry. Sear in very hot clarified butter for 40 seconds per side to caramelise the exterior without raising the internal temperature. Rest 3 minutes. Slice on the bias.`,
      `To plate: arrange two slices of pheasant breast and a crisped leg confit disc on the plate. Place the cider-braised shallot alongside. Spoon the warm jus in a crescent around the proteins. Shave black truffle generously over the entire composition using a mandoline. Finish with fleur de sel and serve immediately while the truffle aroma is at its most volatile.`,
    ],
    source_url: 'https://www.granthachatz.com/recipes',
    image_url: 'https://www.themealdb.com/images/media/meals/qvrwpt1511181864.jpg',
  },
  {
    title: `Turbot with Champagne Beurre Blanc and Caviar`,
    chef: `Joël Robuchon`,
    description: `An epitome of classical Michelin-starred French technique: a thick turbot fillet is poached in a court-bouillon then finished under a gleaming salamander, served in a pool of champagne beurre blanc emulsified tableside by the gradual mounting of cold butter into a reduction of vintage Champagne and shallots. A spoonful of Oscietra caviar is draped across the fish just before service, its salinity cutting through the sauce's lush richness in a single, perfect bite. The plate is the pinnacle of luxurious simplicity.`,
    cuisine: `French`,
    difficulty: `hard`,
    prepTimeMin: 45,
    cookTimeMin: 30,
    servings: 4,
    ingredients: [
      `4 portions thick-cut turbot fillet (150g each), skin on`,
      `1 litre court-bouillon (water, white wine, shallot, peppercorns, bay, parsley stems)`,
      `1 bottle vintage Brut Champagne`,
      `4 shallots, finely minced`,
      `250ml heavy cream`,
      `300g cold unsalted butter, cubed`,
      `60g Oscietra caviar`,
      `Fresh chervil and chive batons for garnish`,
      `Lemon juice to taste`,
      `White pepper, fine sea salt`,
      `1 tbsp crème fraîche`,
    ],
    steps: [
      `For the court-bouillon: combine all ingredients in a wide shallow pan, bring to a simmer, and cook 20 minutes. Strain and reserve warm. The court-bouillon should smell gently of the sea.`,
      `For the champagne beurre blanc: combine finely minced shallots with 300ml Champagne in a small saucepan. Reduce over high heat until only 2 tablespoons of syrupy liquid remain. Add cream and reduce again by half. Begin whisking in cold butter, one cube at a time, over the lowest possible heat — the sauce will emulsify into a thick, pale gold velvet. Season with salt, white pepper, and a squeeze of lemon. Pass through a fine sieve if a silky texture is desired. Keep warm in a bain-marie, whisking occasionally.`,
      `Score the turbot skin with three shallow cuts to prevent curling. Season generously with salt and white pepper on both sides. Bring the court-bouillon to 80°C (just below a simmer). Lower the turbot portions in and poach for 8–10 minutes, maintaining the temperature precisely. The fish is done when it flakes gently when pressed — it should remain pearlescent in the very centre.`,
      `Lift the turbot from the court-bouillon with a fish spatula. Place on a rack and glaze the skin under a very hot salamander or grill for 2–3 minutes to crisp it slightly and colour the edges.`,
      `To plate: ladle 4 tablespoons of warm champagne beurre blanc into a deep, warmed plate. Place the turbot in the centre, skin-side up. Crown the fish with a generous spoonful of Oscietra caviar just before the plate leaves the kitchen. Garnish with chervil sprigs and chive batons. Serve at once.`,
    ],
    source_url: 'https://www.foodandwine.com/recipes/pan-seared-turbot-champagne-butter-sauce',
    image_url: null,
  },
  {
    title: `Oops! I Dropped the Lemon Tart`,
    chef: `Massimo Bottura — Osteria Francescana`,
    description: `Born from a genuine kitchen accident when a pastry chef dropped a lemon tart, Bottura immortalised the broken result as a plated dessert-entrée metaphor for imperfection as beauty. A perfectly made Italian lemon tart is 'dropped' onto a slate plate — the curd pools, the pastry shatters into shards, and a cloud of lemon cream erupts outward — then dressed with candied lemon zest, basil gel drops, and a scattering of crispy pastry crumble. The dish is a philosophical statement made edible.`,
    cuisine: `Italian (Modernist)`,
    difficulty: `hard`,
    prepTimeMin: 120,
    cookTimeMin: 40,
    servings: 4,
    ingredients: [
      `For the lemon curd: 4 whole eggs, 150g caster sugar, 120ml freshly squeezed lemon juice (4 lemons), 150g cold unsalted butter, diced`,
      `For the pastry: 200g all-purpose flour, 100g cold butter, 60g icing sugar, 1 egg yolk, 2 tbsp ice water, pinch of fine salt`,
      `Zest of 4 unwaxed lemons`,
      `100g caster sugar (for candied zest)`,
      `2 tbsp lemon juice`,
      `For basil gel: 200ml water, 50g basil leaves blanched, 2g agar-agar, 1 tsp sugar`,
      `100ml double cream, whipped to soft peaks`,
      `Micro lemon balm leaves for garnish`,
      `Edible gold leaf (optional)`,
    ],
    steps: [
      `For the sweet pastry (pâte sablée): blitz flour, butter, and icing sugar in a food processor until sandy. Add egg yolk and ice water and pulse until the dough just comes together. Press into a disc, wrap, and refrigerate for 1 hour. Roll to 3mm on a floured surface, line four 10cm tart tins, and blind bake at 170°C for 18 minutes with weights, then 5 minutes without, until golden and crisp. Reserve 1 shell and crumble the remaining three into irregular shards of various sizes.`,
      `For the lemon curd: whisk eggs, sugar, and lemon juice in a heavy-bottomed pan over medium-low heat, stirring constantly until the mixture thickens and reads 82°C on a thermometer. Remove from heat, add cold butter piece by piece, whisking vigorously. Pass through a fine sieve. Press cling film directly onto the surface and refrigerate until fully set, at least 2 hours.`,
      `For the candied zest: peel zest in long strips and blanch three times in boiling water. Simmer in a syrup of equal parts sugar and water for 25 minutes. Remove, cool on a rack, and cut into fine julienne.`,
      `For the basil gel: blend blanched basil with water. Strain through fine muslin. Heat the liquid with agar-agar until dissolved. Cool in a shallow tray. Blend the set gel smooth and pass through a sieve. Spoon into a small squeeze bottle for plating.`,
      `To compose (the 'drop'): on a chilled dark slate or plate, place a large spoonful of lemon curd slightly off-centre, spreading it as if splashed. Arrange irregular shards of the crumbled tart pastry around and over the curd in a radiating, chaotic pattern. Dot with tiny spots of basil gel using the squeeze bottle. Place small soft peaks of whipped cream at the edges. Scatter candied zest over the whole composition. Add a few micro lemon balm leaves. The plate should look like a beautiful accident.`,
    ],
    source_url: 'https://www.theguardian.com/lifeandstyle/wordofmouth/2012/sep/26/massimo-bottura-osteria-francescana-recipe',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Lemon_tart.jpg/900px-Lemon_tart.jpg',
  },
  {
    title: `Suckling Pig with Caramelised Milk Skin`,
    chef: `Ferran Adrià — elBulli`,
    description: `Adrià's treatment of suckling pig at elBulli was a systematic deconstruction: the perfectly tender, lacquer-skinned suckling pig was served with a sheet of dehydrated caramelised milk skin (the milk equivalent of chicharrón) that shatters on the palate, alongside a cold sphere of olive oil encapsulated with sodium alginate. This dish exemplified the elBulli philosophy: every element of a traditional roast is reconsidered, rebuilt, and made to behave in ways the diner could not anticipate.`,
    cuisine: `Spanish (Modernist)`,
    difficulty: `hard`,
    prepTimeMin: 2880,
    cookTimeMin: 240,
    servings: 4,
    ingredients: [
      `1 suckling pig, 4–5kg, quartered by your butcher`,
      `Coarse salt and black pepper`,
      `500ml lard or rendered pork fat`,
      `2 heads garlic, halved`,
      `1 bunch thyme, 4 bay leaves`,
      `1 litre whole milk (for milk skin)`,
      `50g sugar (for caramelising milk skin)`,
      `100ml extra-virgin olive oil (for spheres)`,
      `500ml water`,
      `2.5g sodium alginate (for olive oil spheres)`,
      `5g calcium chloride (for setting bath)`,
      `1g xanthan gum`,
      `Apple cider vinegar to taste`,
      `Smoked salt flakes for finishing`,
    ],
    steps: [
      `For the suckling pig: salt the quarters aggressively inside and out 24 hours in advance. Refrigerate uncovered on a rack to dry-brine the skin. When ready to cook, rinse and dry thoroughly. Roast in a 120°C oven, basting with lard and aromatics every 20 minutes, for 3–3.5 hours until completely tender. Increase heat to 240°C for the final 15 minutes to blister and bronze the skin to complete crackling. Rest 20 minutes.`,
      `For the caramelised milk skin (nata caramelizada): spread whole milk in a wide, shallow, heavy pan and cook very gently at 70°C without stirring. As a skin forms after 20 minutes, lift it carefully with a spatula and lay on a Silpat-lined tray. Repeat until you have several skins. Dust lightly with sugar and caramelise under a blowtorch or under a very high broiler to create a golden, irregular caramelised wafer. Dehydrate in a 60°C oven for 1 hour until crisp and glassy.`,
      `For the olive oil spheres (basic spherification): blend olive oil with xanthan gum until homogenous and slightly thickened. Dissolve sodium alginate in water, blend thoroughly, and let rest 1 hour to remove air bubbles. In a separate container, dissolve calcium chloride in clean water. Using a small round-bottomed ladle or hemisphere mould, drip the oil mixture into the alginate bath — a thin gel membrane will form around each droplet in 90 seconds. Transfer carefully with a slotted spoon to a clean water rinse bath. Each sphere contains liquid oil that erupts on the palate.`,
      `To assemble each serving: carve a portion of suckling pig — ribs and loin — from the rested quarter. The skin should crackle when pressed. Season with smoked salt flakes.`,
      `Plate: lay the pork on the plate, skin-side up. Place a shard of caramelised milk skin diagonally across the pork. Arrange 3 olive oil spheres beside the pig using a small spoon — do not puncture them. Add a few drops of apple cider vinegar to the plate. The dish presents three temperatures and three textures: hot crisp pig, room temperature glassy milk skin, and cool liquid olive oil spheres.`,
    ],
    source_url: 'https://www.elbulli.com/cronologia/1983_2011/es/index.html',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Suckling_pig.jpg/900px-Suckling_pig.jpg',
  },
  {
    title: `Roasted Squab with Foie Gras and Black Truffle Jus`,
    chef: `Guy Savoy — Restaurant Guy Savoy`,
    description: `A dish of immense classical authority: a whole squab (young pigeon) is roasted in a very high oven with the breast remaining rose-pink while the legs are separately confited until silky, then the bird is reassembled with a slice of pan-seared foie gras resting on the breast like a crown. The sauce — a reduction of the squab carcass roasted with Madeira and finished with black truffle juice and shaved truffle — is one of the great luxury sauces of Parisian haute cuisine.`,
    cuisine: `French`,
    difficulty: `hard`,
    prepTimeMin: 90,
    cookTimeMin: 75,
    servings: 4,
    ingredients: [
      `4 whole squab (young pigeon), approximately 400g each`,
      `4 slices grade-A foie gras, 60g each, 1.5cm thick`,
      `30g Périgord black truffle, half grated, half shaved`,
      `Squab carcasses and giblets (reserved)`,
      `100ml Madeira wine`,
      `200ml game or dark chicken stock`,
      `50ml truffle juice (from jar or fresh)`,
      `80g cold unsalted butter`,
      `4 slices white brioche, toasted, for serving`,
      `2 shallots, finely sliced`,
      `1 sprig thyme, 1 bay leaf`,
      `Grapeseed oil, for searing and roasting`,
      `Fleur de sel, cracked black pepper`,
    ],
    steps: [
      `Break down each squab: remove the legs, debone the thighs keeping drumstick attached. Season leg portions with salt and pepper, vacuum seal with thyme and butter, and cook sous vide at 72°C for 4 hours until collagen is fully rendered. The crowns (breasts on bone) are reserved for high-heat roasting.`,
      `For the squab jus: roast carcasses at 230°C for 20 minutes until charred. Transfer to a saucepan with shallots, thyme, and bay. Deglaze with Madeira and cook until syrupy. Add game stock and simmer 30 minutes. Strain through a fine chinois and reduce to 150ml. Add truffle juice and reduce slightly. Mount off heat with cold butter in small pieces. Fold in half the grated truffle. Season.`,
      `Preheat oven to 220°C. Season the squab crowns with salt and pepper. Heat an oven-proof pan over high heat with a thin film of grapeseed oil. Sear the crowns breast-side down for 2 minutes until golden. Turn and roast in the oven for 8 minutes. The breast should rest at 54°C (deep rose). Rest 5 minutes before carving the breasts from the bone.`,
      `Season foie gras generously with salt and pepper. Heat a dry, very hot cast-iron pan until it is beyond smoking. Sear each foie gras slice for 45 seconds per side — it will render dramatically and the exterior will caramelise to mahogany while the interior remains barely warm and quivering. Drain briefly on paper towels.`,
      `To plate: arrange the two carved squab breast slices and a confited leg on each plate. Lay a slice of foie gras across the breasts. Spoon the warm truffle jus around the squab. Lay shaved truffle across the foie gras. Accompany with a small slice of toasted brioche spread with the remaining grated truffle blended with a little softened butter.`,
    ],
    source_url: 'https://www.foodandwine.com/recipes/roasted-squab-foie-gras',
    image_url: null,
  },
  {
    title: `Slow-Cooked Hen Egg, Truffle Toast, and Black Winter Truffle`,
    chef: `Thomas Keller — Per Se / The French Laundry`,
    description: `Thomas Keller's egg dish has become one of the most replicated in all of fine dining: a hen's egg slow-cooked for one hour in its shell at 62.8°C achieves a custard-like white and a thick, flowing yolk that pours out in a single unbroken stream. It is served in a tiny cocotte sitting on a slice of toasted brioche spread with truffle butter, garnished with a warm chive custard, a shower of shaved black truffle, and a pinch of fleur de sel. The dish distils luxury to its barest, most perfect essence.`,
    cuisine: `French-American`,
    difficulty: `hard`,
    prepTimeMin: 20,
    cookTimeMin: 65,
    servings: 4,
    ingredients: [
      `4 very fresh large hen's eggs (highest quality available)`,
      `30g black truffle, shaved paper-thin`,
      `4 slices brioche, cut 1.5cm thick`,
      `60g truffle butter (butter blended with finely grated truffle)`,
      `200ml heavy cream`,
      `4 egg yolks (for chive custard)`,
      `3 tbsp freshly snipped chives`,
      `Fleur de sel`,
      `White pepper`,
      `1 tbsp unsalted butter`,
      `Truffle jus or truffle oil (optional, for finishing)`,
    ],
    steps: [
      `Set your immersion circulator or a precisely controlled water bath to exactly 62.8°C. Gently lower the intact, uncracked eggs into the water bath using a slotted spoon. Cook for exactly 65 minutes, maintaining the temperature to within 0.5°C. The white will be just set to a soft custard consistency and the yolk will be thick, flowing, and warm.`,
      `For the chive custard: whisk egg yolks with heavy cream in a bowl. Season with salt and white pepper. Cook in a bain-marie over very gently simmering water, stirring constantly, until the mixture is thick enough to coat the back of a spoon, approximately 8 minutes. Fold in snipped chives. Pass through a fine sieve. Keep warm.`,
      `Toast the brioche slices until golden on both sides. Immediately spread each slice generously with truffle butter. The butter should melt into the warm brioche.`,
      `To crack and serve the egg: remove the egg from the water bath. Using an egg topper or the back of a heavy knife, cleanly remove the top third of the shell. The egg is now its own vessel. Alternatively, crack gently into a small pre-warmed cocotte.`,
      `To plate: set the brioche toast alongside or underneath the cocotte or shell. Spoon 2 tablespoons of warm chive custard over the egg in the shell. Layer shaved black truffle generously — it should mound over the egg. Add a pinch of fleur de sel. Serve immediately with a small demitasse spoon.`,
    ],
    source_url: 'https://www.foodandwine.com/recipes/thomas-kellers-soft-poached-egg',
    image_url: null,
  },
  {
    title: `Edible Stones — Potato Soup and Hazelnut`,
    chef: `Andoni Luis Aduriz — Mugaritz`,
    description: `Mugaritz's most famous and conceptually daring dish presents the diner with a bowl of what appears to be smooth river pebbles — in reality, potato dumplings coated in a clay-like crust of kaolin and salt that renders them visually indistinguishable from real stones. Diners must break them open to discover the soft, yielding potato interior. The 'bowl' is a pool of warm potato cream with hazelnut oil. The dish asks a fundamental question: can you taste something before you know what it is?`,
    cuisine: `Spanish (Conceptual Modernist)`,
    difficulty: `hard`,
    prepTimeMin: 240,
    cookTimeMin: 60,
    servings: 4,
    ingredients: [
      `600g large floury potatoes (Maris Piper or russet)`,
      `100g edible kaolin clay (food-grade)`,
      `50g coarse sea salt`,
      `400ml whole milk`,
      `200ml heavy cream`,
      `50g unsalted butter`,
      `3 tbsp hazelnut oil`,
      `30g toasted hazelnuts, roughly crushed`,
      `White pepper, fine salt`,
      `1 small garlic clove`,
      `Fresh chervil or hazelnut leaves for garnish`,
    ],
    steps: [
      `Cook whole, unpeeled potatoes in heavily salted water until completely tender, about 35 minutes. Drain and peel while hot. Pass the flesh through a ricer or fine drum sieve while still warm. Season with salt and white pepper.`,
      `Divide the potato into 8 equal portions. Roll each into a smooth, oval shape mimicking the form of a river pebble — slightly elongated, with natural asymmetry. Place on a parchment-lined tray and refrigerate until completely cold and firm.`,
      `Mix edible kaolin clay with enough water to form a thick, smooth paste resembling ceramic slip. Add coarse sea salt and stir to combine. Working quickly, coat each cold potato pebble entirely in the kaolin paste using gloved hands or a spoon, ensuring a uniform layer of 3–4mm. Set on a rack and allow to air-dry at room temperature for 2–3 hours until the clay surface hardens and whitens to a stone-like matte finish.`,
      `For the potato cream: simmer milk and cream with a garlic clove until fragrant. Remove garlic. Combine with remaining potato flesh and butter, blend in a high-powered blender until perfectly smooth. Season. Pass through a fine sieve. Keep warm.`,
      `To serve: warm the potato 'stones' very gently in a low oven (80°C) for 15 minutes until heated through — the clay will not change appearance. Ladle the warm potato cream into the bowl. Arrange 2 potato stones in the soup, barely submerged. Drizzle hazelnut oil in a thin crescent. Scatter crushed hazelnuts and fresh chervil. The server instructs the diner to break the stones with a spoon.`,
    ],
    source_url: 'https://www.mugaritz.com/en/creations',
    image_url: 'https://www.themealdb.com/images/media/meals/kos9av1699014767.jpg',
  },
  {
    title: `Celeriac Baked in Beef Fat with Bone Marrow and Capers`,
    chef: `Magnus Nilsson — Fäviken`,
    description: `One of the great New Nordic dishes of the Fäviken era: a whole small celeriac is buried in still-glowing embers and roasted for three hours until the exterior is charred to carbon and the interior is yielding, smoky, and deeply sweet. It is then excavated at the table, the charred crust cracked open to reveal a golden, creamy interior that is dressed with liquid bone marrow, salted capers, and a hand-pressed flaxseed oil — a composed plate of extraordinary minimalism in which smoke, fat, acid, and the primal are in complete equilibrium.`,
    cuisine: `Nordic (Modernist)`,
    difficulty: `hard`,
    prepTimeMin: 30,
    cookTimeMin: 180,
    servings: 4,
    ingredients: [
      `4 small celeriac bulbs (about 400g each), washed but unpeeled`,
      `4 large marrow bones, halved lengthwise`,
      `2 tbsp salted capers, rinsed`,
      `50ml cold-pressed flaxseed oil or extra-virgin rapeseed oil`,
      `1 tsp red wine vinegar`,
      `Coarse salt and black pepper`,
      `Fresh horseradish, grated, for serving`,
      `Small fresh herb leaves (tarragon, chervil, or wood sorrel)`,
    ],
    steps: [
      `Prepare a wood fire or charcoal grill and allow it to burn down to steady, glowing embers — not flame. The temperature at the coal bed should be approximately 250°C. Nestle the whole, unpeeled celeriac directly into the deepest part of the embers. Cover with additional coals and ash and allow to roast undisturbed for 2.5–3 hours. Turn once at the halfway point with long tongs. The exterior will char completely black.`,
      `With 30 minutes left for the celeriac, season the marrow bones with salt and place them cut-side up on a roasting rack over a baking tray. Roast in a 230°C oven for 18–20 minutes until the marrow has just set to a quivering, liquid consistency and is pulling away from the bone edges. It must not be overcooked — the interior should still tremble when shaken.`,
      `Prepare the caper dressing: combine rinsed capers with flaxseed oil and red wine vinegar. Season with black pepper.`,
      `To excavate the celeriac: remove from the embers using tongs. Place on a board and crack the charred crust with a heavy knife — the crust will shatter. Scoop out the interior flesh in large, irregular pieces, discarding the carbon shell. The flesh should be intensely aromatic with deep smoke, yielding but not mushy, and golden-caramel in colour.`,
      `To plate: arrange the excavated celeriac pieces in the centre of a pre-warmed plate. Spoon the warm bone marrow directly from the bone over the celeriac — it should pool and coat each piece. Dress with the caper-flaxseed oil dressing. Grate fresh horseradish over the top. Scatter herb leaves. The dish should smell of smoke, fat, and the forest.`,
    ],
    source_url: 'https://www.theguardian.com/lifeandstyle/2012/nov/16/magnus-nilsson-faviken-cookbook-recipes',
    image_url: null,
  },
  {
    title: `Honey and Lavender Glazed Duck Breast`,
    chef: `Daniel Humm — Eleven Madison Park`,
    description: `A dish that has defined the EMP style: a Long Island duck breast is dry-aged for seven days to intensify flavour and concentrate the fat, then cooked à la plancha while being basted repeatedly in a glaze of raw wildflower honey, culinary lavender, and lemon thyme until the skin is dark, crackling, and perfumed. The breast is served with a pickled cherry mostarda, a smear of lavender-honey jus, and a few drops of lavender-infused vinegar that brighten the richness of the glazed fat.`,
    cuisine: `American`,
    difficulty: `hard`,
    prepTimeMin: 10080,
    cookTimeMin: 35,
    servings: 4,
    ingredients: [
      `2 Long Island (Pekin) duck breasts, about 350g each`,
      `4 tbsp raw wildflower honey`,
      `1 tsp culinary-grade dried lavender flowers`,
      `3 sprigs lemon thyme`,
      `1 tbsp sherry vinegar`,
      `200ml duck jus (from roasted duck carcasses)`,
      `200g fresh Bing cherries, pitted and halved`,
      `2 tbsp sugar`,
      `3 tbsp red wine vinegar (for mostarda)`,
      `1 tsp brown mustard seeds`,
      `Salt and freshly cracked black pepper`,
      `Lavender vinegar (homemade: 200ml white wine vinegar, 1 tsp lavender, steep 2 days)`,
    ],
    steps: [
      `Dry-age the duck breasts, uncovered on a rack in the refrigerator, for 5–7 days. The skin will darken and firm dramatically. Before cooking, score the skin in a tight crosshatch pattern using a very sharp knife, cutting through the fat but not the flesh. Season generously with salt and pepper. Allow to come to room temperature for 30 minutes.`,
      `For the cherry mostarda: combine pitted cherries, sugar, red wine vinegar, and mustard seeds in a small saucepan. Cook over medium heat until the cherries soften and the liquid reduces to a syrupy glaze, about 12 minutes. Season and reserve warm.`,
      `Warm honey in a small pan with dried lavender and lemon thyme over very low heat for 5 minutes. Strain out the lavender and thyme. Add sherry vinegar — the glaze should be sweet, floral, and slightly tart.`,
      `Place the duck breasts skin-side down in a cold, heavy skillet. Turn heat to medium-low. Cook, pouring off rendered fat regularly, for 20–22 minutes, pressing gently with a spatula to ensure even skin contact. The skin must be deeply golden and crackling. Flip and cook the flesh side for 3 minutes. In the final 5 minutes, brush generously with the lavender-honey glaze every 30 seconds, allowing each coat to caramelise before adding the next. Remove and rest skin-side up, 8 minutes.`,
      `Finish the duck jus with remaining lavender glaze and a splash of lavender vinegar — adjust balance of sweet, floral, and acidic. Slice each duck breast on the bias into 4–5 slices. Plate: swipe duck jus across the plate. Fan the duck slices across the jus. Spoon cherry mostarda alongside. Dot the plate with drops of lavender vinegar. Serve at once.`,
    ],
    source_url: 'https://www.foodandwine.com/recipes/lavender-glazed-duck-breast-cherry-mostarda',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Duck_breast.jpg/900px-Duck_breast.jpg',
  },
  {
    title: `Spherical Olive Oil — Liquid Olives`,
    chef: `Ferran Adrià — elBulli`,
    description: `The dish that launched spherification into the global culinary consciousness: at elBulli, Adrià served what appeared to be a single, plump, glistening green olive in a ceramic spoon. On the palate it burst to release a flood of warm, intensely concentrated extra-virgin olive oil liquid — the texture of a cold olive but the temperature of just-pressed oil. Created using basic spherification with sodium alginate and a calcium chloride bath, this five-bite 'dish' redefined what a sauce or garnish could be.`,
    cuisine: `Spanish (Modernist)`,
    difficulty: `hard`,
    prepTimeMin: 60,
    cookTimeMin: 30,
    servings: 4,
    ingredients: [
      `200ml premium extra-virgin olive oil (Arbequina preferred)`,
      `1g xanthan gum`,
      `2.5g sodium alginate`,
      `500ml cold water (for alginate bath preparation)`,
      `5g calcium chloride`,
      `1 litre cold water (for setting bath)`,
      `1 litre cold clean water (for rinsing bath)`,
      `Green food colouring (chlorophyll-based, natural), to colour`,
      `Fleur de sel, for presentation`,
      `Small piece of sourdough bread (for serving alongside)`,
    ],
    steps: [
      `Prepare the alginate bath (note: in basic spherification the alginate is added to the liquid being spherified): blend the extra-virgin olive oil with xanthan gum at high speed for 2 minutes until the oil is slightly thickened and homogenous — xanthan prevents the sphere from breaking and helps it hold its shape. Add chlorophyll-based colouring to achieve an olive-green colour. Add sodium alginate and blend again thoroughly for 2 minutes. Transfer to a container and refrigerate for 1 hour to remove all air bubbles — bubbles will break the spheres.`,
      `Prepare the calcium chloride setting bath: dissolve calcium chloride in 1 litre of cold water. Stir until completely dissolved. Have a rinsing bath of clean cold water ready alongside.`,
      `Test the spherification: fill a small round-bottomed ladle (half-sphere, about 3cm diameter) with the olive oil–alginate mixture. With a swift, precise motion, lower the ladle into the calcium chloride bath just below the surface and quickly invert it, releasing the oil sphere. Allow to set for exactly 90 seconds — a thin but strong gel membrane will form. Carefully remove with a slotted spoon and transfer to the rinse water. The olive should be perfectly round and gleaming green.`,
      `Work in small batches, producing spheres to order. Each sphere will continue to thicken its membrane over time — serve within 15–20 minutes of spherification. The interior remains entirely liquid.`,
      `To present: place one or two olive spheres in a Chinese ceramic spoon. Add one flake of fleur de sel on top. Arrange on a plate. Instruct the diner to place the entire sphere in the mouth in a single motion and bite gently — the membrane will burst and release the warm olive oil in a single, intense rush. Serve with a thin slice of warm sourdough bread.`,
    ],
    source_url: 'https://www.elbulli.com/cronologia/1983_2011/es/index.html',
    image_url: null,
  },
  {
    title: `New Nordic Reindeer with Lingonberry and Pine`,
    chef: `René Redzepi — Noma`,
    description: `A defining Noma plate from the original Copenhagen restaurant that placed Scandinavian cuisine at the centre of the global conversation: a rack of reindeer loin is grilled over burning birch wood and served with a fermented lingonberry sauce, crispy reindeer-fat rendered chips, a powder of dried pine shoots, and a sauce made from the reduced braising liquid of the bones perfumed with juniper and crowberries. Every element was foraged, fermented, or sourced within hours of the kitchen — an act of radical Nordic terroir.`,
    cuisine: `Nordic (Modernist)`,
    difficulty: `hard`,
    prepTimeMin: 1440,
    cookTimeMin: 75,
    servings: 4,
    ingredients: [
      `600g reindeer loin (or elk/venison loin), trimmed`,
      `Reindeer bones for jus`,
      `200ml lingonberry juice (fermented, 3 days at room temperature with a pinch of salt)`,
      `100g fresh or frozen lingonberries`,
      `50g reindeer or duck fat (for rendering chips)`,
      `100g reindeer fat, thinly sliced (for chips)`,
      `2 tbsp dried young pine shoots (or fresh, dried in dehydrator)`,
      `8 juniper berries, crushed`,
      `100ml crowberry or blackcurrant juice`,
      `200ml game stock`,
      `2 tbsp cold butter (for mounting jus)`,
      `Birch wood chips (for smoking/grilling)`,
      `Fleur de sel, freshly cracked black pepper`,
    ],
    steps: [
      `Ferment the lingonberries: combine fresh lingonberries with lingonberry juice and a pinch of fine salt in a sterilised jar. Leave at room temperature for 2–3 days, pressing down daily. The fermentation adds a sharp, bright lactic acidity. Refrigerate once the desired flavour depth is reached.`,
      `For the reindeer jus: roast bones at 220°C for 25 minutes until browned. Transfer to a pot with crushed juniper, crowberry juice, and game stock. Simmer 90 minutes, strain, and reduce to 120ml. Mount with cold butter off heat. Adjust seasoning.`,
      `For the fat chips: arrange very thin slices of reindeer fat on a Silpat tray. Render in a 160°C oven for 25 minutes until all moisture is expelled and the fat is golden and crisp. Drain on paper towels and season immediately with fine salt.`,
      `Season the reindeer loin generously. Grill over burning birch wood and charcoal at very high heat, turning every 30 seconds for 5–6 minutes total for medium-rare (internal temperature 52°C). The birch wood will impart a distinctive, clean woodland smoke. Rest 8 minutes.`,
      `To plate: slice the loin across the grain into 3 pieces per serving. Arrange on the plate. Spoon the warm jus in a pool beside the meat. Place fermented lingonberries and 3 fat chips alongside. Dust the plate lightly with the pine powder using a fine sieve. Finish with fleur de sel. The dish should smell of birch smoke, juniper, and the boreal forest.`,
    ],
    source_url: 'https://www.noma.dk/philosophy',
    image_url: null,
  },
  {
    title: `Black Cod with Miso`,
    chef: `Nobu Matsuhisa — Nobu Restaurant`,
    description: `Nobu Matsuhisa's signature dish, created in the 1980s and now inseparable from his global restaurant empire: sablefish (black cod) is marinated for 48–72 hours in a sweet white miso, sake, and mirin mixture that penetrates the flesh and caramelises under a broiler to an almost lacquered, bittersweet surface of extraordinary beauty. The fish itself is buttery, yielding, and sweet, the skin blistered to a glossy mahogany. The dish defined a new category of Japanese-Peruvian-Californian fusion.`,
    cuisine: `Japanese-Fusion`,
    difficulty: `hard`,
    prepTimeMin: 4320,
    cookTimeMin: 20,
    servings: 4,
    ingredients: [
      `4 portions black cod (sablefish) fillet, 180g each, skin on`,
      `150g white (shiro) miso paste`,
      `100ml sake`,
      `100ml mirin`,
      `3 tbsp sugar`,
      `For the den miso glaze: 150g white miso, 100ml sake, 100ml mirin, 3 tbsp sugar (heated together until sugar dissolves — this IS the marinade)`,
      `Micro shiso leaves for garnish`,
      `Pickled ginger, to serve`,
      `Steamed Japanese short-grain rice, for serving`,
    ],
    steps: [
      `Make the den miso marinade: combine miso paste, sake, mirin, and sugar in a heavy saucepan over medium heat. Whisk constantly until the sugar dissolves and the mixture just begins to bubble. Do not let it boil aggressively or the sugars will caramelise prematurely. Remove from heat and cool completely to room temperature.`,
      `Pat the black cod fillets completely dry with paper towels. Coat each fillet on all sides with the cooled miso marinade, ensuring an even layer. Place in a zip-lock bag or glass dish, cover tightly, and refrigerate for a minimum of 48 hours — 72 hours is optimal. The fish will take on a deep, almost wet look as the marinade penetrates.`,
      `When ready to cook, remove the fish from the marinade and wipe off the excess with a clean hand or paper towel — a thin coating is what you want, not a thick paste, as the sugar will burn before the fish cooks through. Allow to sit at room temperature for 20 minutes.`,
      `Preheat the oven broiler/grill to its maximum setting (or use a salamander). Line a baking sheet with foil and lightly oil. Place the fish skin-side down. Broil 4–5 inches from the heat source for 3–4 minutes until the surface is dark, caramelised, and spotted with near-black char patches. Transfer the pan to the middle of the oven at 200°C and continue cooking for 8–10 minutes until the fish is opaque throughout and flakes easily.`,
      `To plate: set the black cod fillet, glazed-side up, slightly off-centre on a warm plate. The skin should be mahogany and glossy. Garnish with a few micro shiso leaves. Serve with pickled ginger on the side and steamed rice in a separate vessel.`,
    ],
    source_url: 'https://www.foodandwine.com/recipes/nobu-style-miso-marinated-black-cod',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Nobu_black_cod_miso.jpg/900px-Nobu_black_cod_miso.jpg',
  },
  {
    title: `Venison Tartare with Fermented Mushrooms and Blackberries`,
    chef: `René Redzepi — Noma`,
    description: `A raw preparation showcasing the Nordic obsession with fermentation and precision: hand-chopped saddle of venison is seasoned with a lacto-fermented mushroom garum (a long-aged, umami-rich liquid fermented from cepe mushrooms), dressed with cold-pressed pine oil, and plated with a sharp blackberry gel, crispy lichen chips, and wild herbs foraged that morning. The dish arrives at the table alive with layers of forest flavour — sweet, funky, fermented, and wholly Nordic in spirit.`,
    cuisine: `Nordic (Modernist)`,
    difficulty: `hard`,
    prepTimeMin: 20160,
    cookTimeMin: 30,
    servings: 4,
    ingredients: [
      `400g venison saddle (inner loin), sinew removed`,
      `100ml fermented mushroom garum (cepe mushrooms lacto-fermented with 2% salt for 3–4 weeks, strained)`,
      `2 tbsp cold-pressed pine shoot oil (or fir-infused grapeseed oil)`,
      `150g fresh blackberries`,
      `1g agar-agar (for blackberry gel)`,
      `50g dried and fried lichen chips (Cladonia species, food-grade, dehydrated and flash-fried)`,
      `2 tbsp finely snipped chives`,
      `Small wood sorrel leaves, ramson flowers, or other foraged herbs`,
      `Fleur de sel, cracked black pepper`,
      `1 tsp apple cider vinegar (for tartare seasoning)`,
    ],
    steps: [
      `Prepare the mushroom garum (weeks in advance): combine finely ground dried cepes with 2% of their weight in fine sea salt. Pack tightly in a sterilised jar, cover, and ferment at room temperature for 3–4 weeks, pressing down daily. Strain through fine muslin. The resulting liquid is intensely savoury and umami-rich — use sparingly.`,
      `For the blackberry gel: blend 100g blackberries until smooth. Strain through a fine sieve to remove seeds. Heat the juice with agar-agar (2g per 200ml), whisking until fully dissolved. Pour onto a flat tray and refrigerate until set. Blend the set gel smooth in a blender, season with a few drops of apple cider vinegar, and pass through a fine sieve. Transfer to a squeeze bottle.`,
      `For the lichen chips: source dried culinary lichen. Dehydrate further in a 60°C oven for 2 hours. Flash-fry in 200°C neutral oil for 3–4 seconds until they expand and crisp. Drain on paper towels and season immediately with fine salt. Reserve at room temperature.`,
      `For the venison tartare: ensure the venison is very cold (near freezing) before cutting. Slice into 5mm slices, then into strips, then finely and evenly hand-chop to a coarse tartare consistency. Do not use a machine — the texture will be destroyed. Season with fleur de sel, cracked black pepper, chives, and 1 tsp mushroom garum. Dress with pine oil and a few drops of apple cider vinegar. Taste and adjust — it should taste of the forest.`,
      `To plate: place a neat quenelle or mounded spoonful of venison tartare at the centre of a cold plate. Dot the blackberry gel in irregular spots around the tartare. Place 3 lichen chips at angles around the quenelle. Scatter wood sorrel and other foraged herbs. Add a few fresh blackberry halves. Dress with drops of additional pine oil. Serve immediately — the tartare must be ice-cold.`,
    ],
    source_url: 'https://www.noma.dk/philosophy',
    image_url: null,
  },
];

const checkExists = db.prepare('SELECT id FROM recipes WHERE title = ?');
const insertRecipe = db.prepare(`
  INSERT INTO recipes (id, title, description, cuisine, difficulty, prep_time_min, cook_time_min, servings, tags, source_url, created_at, updated_at)
  VALUES (?, ?, ?, ?, ?, ?, ?, ?, NULL, ?, ?, ?)
`);
const insertIngredient = db.prepare(`
  INSERT INTO recipe_ingredients (id, recipe_id, name_override, step_order)
  VALUES (?, ?, ?, ?)
`);
const insertStep = db.prepare(`
  INSERT INTO recipe_steps (id, recipe_id, step_number, instruction)
  VALUES (?, ?, ?, ?)
`);
const insertMedia = db.prepare(`
  INSERT INTO recipe_media (id, recipe_id, type, url_or_path, caption, is_primary, sort_order)
  VALUES (?, ?, 'image', ?, 'Primary recipe photo', 1, 0)
`);

const insertAll = db.transaction((recipes: Recipe[]) => {
  let inserted = 0;
  for (const r of recipes) {
    const existing = checkExists.get(r.title);
    if (existing) {
      console.log(`  ⏭  Skipping (exists): ${r.title}`);
      continue;
    }
    const id = ulid();
    const ts = now();
    insertRecipe.run(id, r.title, r.description, r.cuisine, r.difficulty, r.prepTimeMin, r.cookTimeMin, r.servings, r.source_url, ts, ts);
    r.ingredients.forEach((name, i) => insertIngredient.run(ulid(), id, name, i));
    r.steps.forEach((instruction, i) => insertStep.run(ulid(), id, i + 1, instruction));
    if (r.image_url) insertMedia.run(ulid(), id, r.image_url);
    console.log(`  ✅ Inserted: ${r.title}`);
    inserted++;
  }
  return inserted;
});

const count = insertAll(RECIPES);
console.log(`\nDone — ${count} new recipes added.`);
